### ISSUE TITLE
Using Swarm-error-document may return invalid resource without HTTP error

### ISSUE THREAD

**Issue by agazso** [ethersphere/bee#1005]
#### Summary
When using the `swarm-error-document` header, if a resource is not found then the resource specified in the header is returned with a 200 (HTTP OK) status. This may return in some cases an invalid resource without the user being aware of an actual error.

Let's say you have a website with different files (`index.html`, `app.js`, `app.css`, `error.html`) and the `error.html` is set using the `swarm-error-document` header. Then in some cases when due to a network error you the node fails to find a file (for example `app.js`) then it will return `error.html` instead which will break the page.

I think the problem is with the current working is that because it's returning with an OK status, it's indistinguishable if there was a network error or you used an invalid path that does not exist. Because it's also not possible to query the contents of the manifest from the API it makes working with manifests difficult.

#### Expected behavior
In case of there is an error it would be better to return the error code as well.

**Comment by Eknir** [comment]
@agazso , is this one fixed now?

**Comment by agazso** [comment]
It's not fixed.

**Comment by Eknir** [comment]
If I understand this correctly, if you have a manifest uploaded with an error document, then basically, when one of the files in the manifest cannot be found, there is a redirect to the error document. Apart from showing the content of the error document, there is no notion of informing the user otherwise that an error happened?

The original implementation of this error document was done by @janos and @zbiljic , at that time. I was also involved and, to me, the intention would be to allow the dapp developer to show a custom error page when the is not loading. I understand right now, that this feature actually makes it very difficult to work with the manifest if you specify an error document.

@janos @zbiljic , could you please share here your reasoning on implementing this error document, but without actually returning an error code? Perhaps @agazso misses something or there was another usecase intended?

@agazso , would you, as a dapp developer use the error-document feature if it would return an error code together with the document?

**Comment by janos** [comment]
Error document is to "catch all" non existing paths under a specific path in order to have externally linkable contend with js routers in history mode, by serving the same html page with js that would render correct content under the path and not to return the not found page. Similar functionality exists in the swarm original manifest, but it is not optional, it is implicit. I see that this is very controversial feature, and being such, maybe should be removed.

**Comment by agazso** [comment]
In the current form I wouldn't use this feature because it provides an overly simplified model of handling errors that is not suitable for most cases.

For example it returns the error document in the case when a document could not be found because of a swarm network issue. But that is totally undeterministic and if that happens it may also happen that the error document itself cannot be returned as well, so then the behavior that the user (who tries to access the documents) will see is undefined.

**Comment by janos** [comment]
The only case where this document should be served is when the path is not found in the manifest, not on any error. I believe that this was previously discussed and that the simple change was identified.

**Comment by agazso** [comment]
In this case I think it would be better to call this `swarm-missing-document` or something similar because the current name suggests that it is returned in case of any error which is not the case.

**Comment by zbiljic** [comment]
It might be possible to return `404` status code when error document is returned (using `w.WriteHeader(http.StatusNotFound)`).
In this case the content of (optional) error document is returned so that it can be shown if configured and we it should be displayed.

I do not know how this would affect different possible SPA, or other websites.

**Comment by agazso** [comment]
This could work. I was not sure what happens when you request a `.js` file and the server returns 404, but in all the browsers it behaves as expected, i.e. an error is generated and the javascript is not interpreted in any way.

**Comment by acud** [comment]
@agazso can we close this?

**Comment by agazso** [comment]
We just discussed potential fixes and seemed to arrive to a conclusion that the error document should also return 404 as response code.

But as far as I know this fix has been not implemented.
