### ISSUE TITLE
Lazy-sync local chunks with the network

### ISSUE THREAD

**Issue by tmm360** [ethersphere/bee#1097]
# User story

## Story

I'm an node operator that is maintaining a set of data on Swarm. This data set has periodic updates, and any update replaces the previous one.

Each update contains data chunks that can be useful or unuseful for users; a data chunk is useful when at least an user requests it, it's unuseful when no users requests it, and a successive update discard it.

As a data maintainer I've a cost on upload chunks to the network, so I want to minimize traffic of unuseful data chunks. What I want is to publish with each update only the reference of the last data set, and use Global Pinning to make it reachable.

When an user request a chunk, if it has already been requested and it has not been dropped by caching nodes, the network will reply with it. If it doesn't exists, the Global Pinning implementation will require to me to upload it. In this way only useful chunks will be uploaded.

## Acceptance criteria

When I upload a file to a Swarm gateway, I need a way for say "use lazy-sync", or something like this. The effect must be that the file (and relative chunks) will be local pinned, and the sync of the file with the net never starts. Using node address I will be able to use Global Pinning, and make data accessible on the network on a successive step.

## Background

At Etherna we need this solution for implement MDBee: https://github.com/Etherna/mdbee
MDBee wants to keep synced a MongoDB instance with a Swarm copy of data. Documents evolves in time, but some changes could come before that previous document has ever been read by someone. Any upload of unwanted documents would be a waste of traffic. More information on the paper.

**Comment by Eknir** [comment]
Hi @ttmm360!

First of all, thank you for taking the time to make this issue. I see the use case and how it would provide value to your users.

To support this feature as you have in mind, the Bee node must support an upload, but don't sync operation. Additionally, global pinning must be extended with issue #891 to efficiently request upload a big amount of chunks for global pinning.

Unfortunately, the Swarm team does not have the bandwidth at this moment to dive into this specific issue before our 1.0 release. 

I do believe, however, that you will still be able to have this feature, even without any changes to the Bee node:

1. You register a special handler to your PSS inbox, looking for a recovery message, requesting the root chunk of the file. Normally this recovery message would trigger the recovery protocol of your global pinning node, but since you didn't upload anything this doesn't happen
2. The message triggers a process outside the bee that would upload everything under that specific root hash
3. The user will be able to download the download the file when everything is uploaded. He/she might need to retry once. 

Let me know what you think about this!

**Comment by tmm360** [comment]
Thank you @Eknir!
This can be a good workaround and I appreciate your suggestion, but luckily this isn't a blocking feature for us. The MDBee project is currently considered an experiment, and we can postpone this optimization for when feature will be ready, also after 1.0 release.

**Comment by tmm360** [comment]
ping
