### ISSUE TITLE
Sync never reaches complete, sent figure keeps increasing

### ISSUE THREAD

**Issue by significance** [ethersphere/bee#1141]
#### Summary
Sync never reaches complete, while the sent figure keeps increasing.

#### Steps to reproduce
Keep checking the tag count, the sent figure keeps increasing. You may use branch 21_1_11-t of sig-smoke-tests (sst) to try to replicate.

#### Expected behavior
Expected sync+seen figure to equal total.

#### Actual behavior
Sent figure keeps increasing.

Logs attached.

[Archive.zip](https://github.com/ethersphere/bee/files/5848533/Archive.zip)

The output from sst for a smaller (5mb) blob is below:

The struct printed is 

```
		type TagResponse struct {
			Total int
			Split int
			Seen int
			Stored int
			Sent int
			Synced int
		}
```

```
sig :: github.com/significance/sig-smoke-tests-go 1 » go run main.go
postTo http://localhost:1633/files
postType application/octet-stream
tmpFolder tmp
getFromTemplate https://bee-%d.gateway.ethswarm.org/bytes/%s
postSize 5000000
batchSize 1
getTestTimoutSecs 100
sleepBetweenBatchMs 300
maxNode 69
jobID 1611223505575118000
1 / 1
posted a2bff596212f89195c77f619003590153d6be0ae4e7461cd43eda8329c264118
syncing 0 {1234 1234 0 1234 115 100}
syncing 0 {1234 1234 0 1234 136 129}
syncing 0 {1234 1234 0 1234 184 176}
syncing 0 {1234 1234 0 1234 244 230}
syncing 0 {1234 1234 0 1234 301 287}
syncing 0 {1234 1234 0 1234 369 360}
syncing 0 {1234 1234 0 1234 438 421}
syncing 0 {1234 1234 0 1234 494 470}
syncing 0 {1234 1234 0 1234 561 538}
syncing 0 {1234 1234 0 1234 629 604}
syncing 0 {1234 1234 0 1234 692 667}
syncing 0 {1234 1234 0 1234 753 726}
syncing 0 {1234 1234 0 1234 818 791}
syncing 0 {1234 1234 0 1234 887 859}
syncing 0 {1234 1234 0 1234 953 924}
syncing 0 {1234 1234 0 1234 1021 989}
syncing 0 {1234 1234 0 1234 1087 1055}
syncing 0 {1234 1234 0 1234 1154 1120}
syncing 0 {1234 1234 0 1234 1201 1169}
syncing 0 {1234 1234 0 1234 1240 1209}
syncing 0 {1234 1234 0 1234 1252 1230}
syncing 0 {1234 1234 0 1234 1252 1230}
same 0 {1234 1234 0 1234 1252 1230}
syncing 0 {1234 1234 0 1234 1252 1230}
same 1 {1234 1234 0 1234 1252 1230}
syncing 0 {1234 1234 0 1234 1252 1230}
same 2 {1234 1234 0 1234 1252 1230}
syncing 0 {1234 1234 0 1234 1252 1230}
same 3 {1234 1234 0 1234 1252 1230}
syncing 0 {1234 1234 0 1234 1252 1230}
same 4 {1234 1234 0 1234 1252 1230}
syncing 0 {1234 1234 0 1234 1252 1230}
same 5 {1234 1234 0 1234 1252 1230}
syncing 0 {1234 1234 0 1234 1252 1230}
same 6 {1234 1234 0 1234 1252 1230}
syncing 0 {1234 1234 0 1234 1252 1230}
same 7 {1234 1234 0 1234 1252 1230}
syncing 0 {1234 1234 0 1234 1252 1230}
same 8 {1234 1234 0 1234 1252 1230}
syncing 0 {1234 1234 0 1234 1252 1230}
same 9 {1234 1234 0 1234 1252 1230}
syncing 0 {1234 1234 0 1234 1262 1230}
syncing 0 {1234 1234 0 1234 1272 1230}
^Csignal: interrupt
```

**Comment by Eknir** [comment]
@zbiljic , since you are working on tags, can you take care of this report? I assume your work will fix this.

**Comment by Eknir** [comment]
@zelig @acud , could it be explained that `synced + seen` doesn't equal `total` because some chunks are never sent out because they belong to the nn ? If so, shouldn't we not just increase `synced` for those chunks that are not send by push sync because they belong to nn?

**Comment by zbiljic** [comment]
This issue talks about two separate things.

As noted, any 'larger' content will be broken into multiple chunks. The values in `/tags` API response relate to chunk counts.
- `seen` state increments during upload (content splitting) in the case some chunk is already present in localstore.
- `sent` state is incremented for each push chunk delivery
  - push will be attempted to multiple peers
  - in this case (from logs) the error that was happening was related to pricing - `receive receipt from peer`; which is when node tries to receive receipt, just after incrementing `sent` state
  - so to be fair, the chunk was "sent" (just not paid for ?)
- `synced` state should be incremented when the chunk is 'sent' successfully
  - since (in this case) it does not complete full circle, i.e. receiving receipt, it will not increment

This whole flow also depends on the peers that the uploading node is connected to (some peer may not be calculated as closest peer).

Back to this issue. The `sent` figure increases because the chunks are being sent (pushed) to other peers, although probably same peers again and again (until receiving receipt succeeds). And `sync`+`seen` figure should be the same, however since some chunk(s) (in this case probably `4` chunks, although I do not exclude that there might be some other problem with counters), it will not reached same value as `total` (`split`).
