### ISSUE TITLE
Tag polling on multiple uploaded same file

### ISSUE THREAD

**Issue by nugaon** [ethersphere/bee#1146]
#### Summary

When the same data are uploaded twice, the tracking (via tag pollings) of the uploads act differently.
On the first update, after some polling I get back the expected result (`synced` equals `stored`).
Second time with a new tag the `synced` remains 0 after several polling, it doesn't change.

The documentation about the [GET /tags/{uid}](https://docs.ethswarm.org/api/#tag/Tag/paths/~1tags~1{uid}/get) would be nice if it could be a little bit more detailed, not every property's role is clear.

#### Steps to reproduce

- create tag
- upload dir on `dirs` EP
- create tag
- upload the same directory and pass the newly generated tag's uid
- polling tag on `tags/{uid}`

#### Expected behavior

On second upload the `synced` should be equal to the `stored` after a while.

#### Actual behavior

secondly generated tag remains the same on polling:
```js
{
  total: 0,
  split: 8,
  seen: 8,
  stored: 8,
  sent: 0,
  synced: 0,
  uid: 4003410846,
  name: 'unnamed_tag_1611325958',
  address: '',
  startedAt: '2021-01-22T14:32:38.541273654Z'
}
```

**Comment by zbiljic** [comment]
Please note that this is expected behavior. Since you uploaded same content twice, the second time `seen` state is incremented. Re-uploaded chunks will not be synced since they are already locally stored, and assumed to have already been `synced` in some previous time.

Please note that there is ongoing effort to "improve" (simplify) this API, in order to remove doubts users have about tag results.

**Comment by nugaon** [comment]
So in order to tell about chunks whether they are populated on Swarm or not, I have to check 2 conditions now:
```js
if (tagStatus.synced === tagStatus.stored || tagStatus.seen === tagStatus.stored) {
  //populated
}
```
am I right?

**Comment by zbiljic** [comment]
Now I am not entirely sure what you mean with "populated on Swarm or not", however if you refer to checking if file can be considered as updated (and synced to network), in the current state of API, there would still be single condition, with two parameters, i.e.:

```js
if (tagStatus.stored === tagStatus.seen + tagStatus. synced) {
  //populated
}
```

This also would depend on when exactly are you checking this condition, because `stored` is incremented as the uploaded content is being split. This means that in theory (something blocks - highly unlikely) it could be possible that in an instant value of `stored` to be equal to `seen` + `synced`, while in fact not all chunks are actually stored.

Value that is updated once file is fully stored (locally processed on the node, at least), is `total`. That means that just before returning response after uploading to some endpoint, happens function call to `tags.DoneSplit(address)`, which copies `split` value into `total` value for tag (and populates `address` field).

Looking at your tag response, it would seem that even the upload has not completed yet? Because the value for `total` is `0`, and also the `address` is empty.

In that case it might then be better to use `total` as base to validate that file is completed upload:

```js
if (tagStatus.total === tagStatus.seen + tagStatus. synced) {
  //populated
}
```

And to use `stored` vs `seen` + `synced` for some progress bar (if needed).

There is also whole another detail here in the case when tag is used multiple times, into which I will not go in this time.

I am sorry, I see now that I started rambling a bit, and introduced few new details. Anyway, this whole tag API is being reconsidered at the moment, and this helped me understand some things as well. If you (or anyone else) has suggestion what would be "better" for this API, feel free to comment on #918. You can also track my progress for changing this API on #1148.

P.S.
Here is snipped of source code with explanations about there different tag states from [`pkg/tags/tag.go`](https://github.com/ethersphere/bee/blob/f8054e91c87c22dfa6c0b8dd13c41e6d4792dea6/pkg/tags/tag.go):

```go
Total  int64 // total chunks belonging to a tag
Split  int64 // number of chunks already processed by splitter for hashing
Seen   int64 // number of chunks already seen
Stored int64 // number of chunks already stored locally
Sent   int64 // number of chunks sent for push syncing
Synced int64 // number of chunks synced with proof
```

**Comment by Eknir** [comment]
Issue number #1051 would change this and would actually reupload the content to the network if it was already seen

**Comment by nugaon** [comment]
for me the `total` remains 0 even when I already reach the content through my BZZ EP and also I can load on the other node's BZZ EP as well

**Comment by zbiljic** [comment]
@nugaon Not sure if my comment here was comprehensive enough (I wrote several on similar issues regarding this).

The `total` will remain forever zero if you created a tag manually, and used that tag for upload. For the `total` to be changed (to the value of `split`), 'someone' must say that the upload is completed.
In the case where you directly upload to `/bytes`, `/files`, `/dirs` endpoint, new tag will be created, and once upload of content is completed, you will receive reference for the content, and the tag will be marked as "done", which means `total` will get the copied value from `split`, and the `address` will be added to tag (same address returned after upload).
When tag is manually created via `/tags` endpoint (as you mentioned in the steps in this issue), that tag can be used on one or multiple upload(s), and on the end of whatever upload operations performed must again be manually marked as "done" (by making `PATCH` request to `/tags/{id}`) in order to `total` value not be `0`.

**Comment by Eknir** [comment]
@significance , heads up. Can we somehow copy what @zbiljic writes here in our docs?

**Comment by zbiljic** [comment]
@Eknir please note that all some of my comments may be obsolete once #1148 is merged.
