### ISSUE TITLE
`total` property of Tag 

### ISSUE THREAD

**Issue by nugaon** [ethersphere/bee#1224]
#### Summary

`total` Tag property of uploaded file **when use file streaming** gets wrong chunk count value (instead of X, it remains 2).
This initial value is not updated during the stream upload.
`synced` and `processed` end with correct values when uploading finishes.

The file is successfully uploaded and can be fetched through the `files` EP, but `total` remains 2.

#### Steps to reproduce

* create tag
* upload file via `fs.createReadStream(path)` on `files` EP
* polling tag state

#### Expected behavior

`total` updates correct chunk count number after uploading to local Bee node.

#### Actual behavior

`total` remains 2 on stream uploading.

swarm-cli PR about it: https://github.com/ethersphere/swarm-cli/pull/11
![Screenshot from 2021-02-09 11-40-05](https://user-images.githubusercontent.com/50576770/107368409-d002e000-6ae0-11eb-8b8d-f315579b31a9.png)

**Comment by Eknir** [comment]
Thank you for creating this issue. In your example, you mention that it always stays `2`. Is this the case for arbitrary-size files, or is it just that it is off by one (total-1)?
I believe this issue is at length discussed at https://github.com/ethersphere/bee/issues/1244 and will therefore close this issue. If you disagree and believe that your issue points to something else you can reopen it.
