### ISSUE TITLE
Idea: debug endpoint for deleting all data from a node

### ISSUE THREAD

**Issue by agazso** [ethersphere/bee#1264]
It would be good for testing if there were an endpoint for deleting all data from a node. Similar to the
https://docs.ethswarm.org/debug-api/#tag/Chunk/paths/~1chunks~1{address}/delete endpoint but for all chunks and also related data (tags, etc.)

Otherwise it's very difficult to reliably test some features. For example the Find feed endpoint (and as a consequence the `/bzz` endpoint) returns different data based on what is stored on the node.

**Comment by acud** [comment]
i am not really convinced this is a good idea. you can test stuff reliably by generating random data, getting different chunk addresses every time you test something. then tests do not interfere with each other. swiping a node means we also need to swipe parts of the state store, since intervals inside the localstore will potentially get messed up and screw with pull sync logic. there is also no guarantee that you don't swipe the node while some chunks are being received, putting the node into some corrupt state. also, for the record, I would really be happy _not_ to have the chunk delete endpoint. it was introduced due to needs in integration testing, however I feel it increases our attack surface

**Comment by agazso** [comment]
For the record many of the bee-js tests are integration tests and indeed we are using random data for testing. However this has its own issues:
- Tests become unreproducible without effort. We would need to log the random seeds we are using the time a random is generated so that the tests can be replayed and have a way to provide it as an argument for the tests being run. Currently our test runner is not prepared to do this so we would need to commit to time to work on a general solution or do this manually every time there is a problem to be debugged. It also makes it more difficult to share an issue with the exact same values between the JS and Go codebases.
- It introduces flakyness. As different chunk addresses map to different nodes on the network the distribution of the data can be different between test runs. In turn this can lead to network latencies or lookup strategies behaving differently therefore making basic assumptions or reasoning about test scenarios more difficult. In practice this often manifests in tests failing "sometimes".

With that said I understand the issues about messing up syncing. Our alternative idea is to fire up empty nodes and run the tests on them for each test that would require this level of isolation, but it's more time consuming when running the tests.

Regarding that it's an attack surface: I think that the debug API has been (mis-)used to provide private (to the node owner) functionality instead of exposing such functionality on a private API. Examples for such endpoints are balance, chequebook etc. Fixing that could reduce the attack surface, because then the debug API could be only used for (integration) testing.

**Comment by Eknir** [comment]
@agazso, about the flakyness and the unreproducability; wouldn't making these tests more deterministic give you a false sense of security? Your tests may always pass with a certain chunk address, but if they don't always pass with _all_ chunk address, this points to a problem. The vision of Janos with integration testing was that we actually use the network as it would be used also in real life. Deleting chunks is not an operation that any node operator is expected to do. Thus, orchestrating your integration tests with this would be against the original vision. 

Now, of course we can change this, but I feel that if it would be possible to adapt the testing suite in order to withstand non-determinism in integration tests, that this would yield more reliable outcomes of tests and would thus be preferred.

Furthermore, by introducing endpoints that are not common, we may actually cause the node to fail, causing the tests to fail. In this case, we don't know if the function is actually broken, or if the way we manipulate the node is running in some edge-case scenario that was not predicted when making the feature (as @acud points out, we may mess up intervals in the statestore here).

**Comment by agazso** [comment]
@eknir There are different types of possible tests and as I mentioned before we consider our tests to be integration tests in the sense that for a given input we expect a given output from Bee. You are correct in that this does not cover all possible cases. On the other hand we assume that the chunks are equivalent and anyways it's impossible to test all possible scenarios. In our case it's fine because we just want to verify if the Javascript code does what we expect it to do in the case of certain responses.

We do not consider that the Javascript tests would provide the only integration testing for Swarm (there are Beekeeper tests for that AFAIK). It would be also possible to mock the responses in the Javascript code from Swarm and test the code that way, however that would require to verify manually before each release if the API responses haven't changed compared to the hardcoded responses. We decided that it was easier to write test against a running Bee environment, but that resulted in other tradeoffs, for example the issue in question.

By the way after consideration and discussion with the JS team we decided to build our own test environment where it's possible to start nodes from a known (empty) state and run the tests deterministically that way. That means that this issue can be closed.

Regarding the network testing: I think it's a good idea, but I think it's a different type of test than integration test (I would classify as smoke testing), therefore it's not a replacement for integration tests but rather a complementary approach instead. In integration testing determinism is important (so that when you find a problem it's easy to reproduce and ultimately fix) whereas in the network testing the observations and the results could be viewed statistically, on a macro level for emergent behaviors.
