### ISSUE TITLE
peers added from debugapi don't end up in kademlia

### ISSUE THREAD

**Issue by acud** [ethersphere/bee#1414]
#### Summary

Adding a peer from the debugapi is not showing afterwards in `/topology`.

#### Steps to reproduce

Add the peer, then query `/topology`. The peer will not be found.

#### Expected behavior

Peer found in topology

#### Actual behavior

No peer found.

Sidenote: we used to have notification logic wired up into the p2p connect method, but this apparently got lost at some point when this got refactored.

**Comment by r0qs** [comment]
I believe that adding the following line after the [s.p2p.Connect](https://github.com/ethersphere/bee/blob/master/pkg/debugapi/peer.go#L30) in the peer connect handler of the debugapi would fix the problem since the peer is only not added in the topology of the caller node:

```go
err = s.topologyDriver.AddPeers(r.Context(), bzzAddr.Overlay)
```

Or do you think that it is necessary to change the current behavior of the [Connect](https://github.com/ethersphere/bee/blob/master/pkg/p2p/p2p.go#L22) in the p2p service?

**Comment by acud** [comment]
Actually no. Calling `AddPeers` will not cause the peer to show up in kademlia, unless it tries to actively dial the peer. We should call the `Connected` hook on kademlia either from the p2p abstraction or from the debugapi. Whatever works best

**Comment by Eknir** [comment]
Is this already resolved?

**Comment by r0qs** [comment]
Hi @Eknir ,

As far I'm aware, the problem is not solved yet.
As @acud mentioned, we should use `Connected` to notify kademlia about the new peer, but the topology driver does not have access to the connection notifier methods anymore.

The easy solution would be to undo part of what was done in the PR https://github.com/ethersphere/bee/pull/641 calling the Connected in debug api:
```go
s.TopologyDriver.Connected(r.Context(),  p2p.Peer{Address: bzzAddr.Overlay}, true)
```
And adding the `Notifier` interface from the p2p package back to the topology `Driver` interface, so the debug API will have access to the Connected method. Like so:

```go
type Driver interface {
	Notifier
	...
}

type Notifier interface {
	Connected(context.Context, p2p.Peer) error
	Disconnected(p2p.Peer)
}
```

But, as pointed out by @acud in a previous conversation, the problem is that the PR https://github.com/ethersphere/bee/pull/1352 introduces the concept of an oversaturation limit and it will not allow a node to connect to a peer if the target peer is [oversaturated](https://github.com/ethersphere/bee/blob/master/pkg/kademlia/kademlia.go#L732).

We discussed an alternative solution introducing a boolean flag to the `Connect` method to bypass the oversaturation limit.
The flag would be false by default, and it would be true if the connection request were trigger by the debug API.

I still need to add some tests, but if this solution sounds good enough for you, it can be found in this PR https://github.com/ethersphere/bee/pull/1585

**Comment by Eknir** [comment]
@r0qs , thanks for the elaborate answer!

Am I correct that it is resolved now?

**Comment by r0qs** [comment]
yes :)
