### ISSUE TITLE
Redefine neighborhood depth and calibrate low water mark

### ISSUE THREAD

**Issue by Eknir** [ethersphere/bee#1418]
Issue #1240 stipulated the problem of the asymmetric neighborhoods. This can be partly remedied by applying the following changes:

1) The `low water mark` for non-neighborhood bins should be greater or equal to the redundancy parameter (aka neighborhood size). 
2) Set the depth, in such a way to not allow unsaturated bins outside the depth

Old situation example with neighborhood size = 4
-----------
8 | 1
7 | 0
6 | 2
5 | 0
--- depth
4 | 1
3 | 4
2 | 4
1 | 4

In this case, there might be an asymmetry, as the peer in bin 4 might believe the peers in my neighborhood belong to his neighborhood. Because we have the low water mark right now at 1, we don't know if there is indeed 1 peer, or if there is symmetry. This confusion is fixed by point 1. If there is asymmetry, then point 2 fixes that we set the depth in such a way to include bin 4.

**Comment by acud** [comment]
> Because we have the low water mark right now at 1

There's a mixup of wrong terms used here.
Low watermark is set at 2 not 1, and it defines the size of peers to determine the depth. This is clearly articulated in the code:
```go
	nnLowWatermark         = 2 // the number of peers in consecutive deepest bins that constitute as nearest neighbours
```

I think that as of such the depth calculation should be changed in the following manner - right now it does a sweep from deepest to shallowest to detect the depth candidate, then does a sweep from shallow to deep to detect empty bins and selects whatever is _shallower_. I think that the second sweep should just be changed to detect whether there are unsaturated bins instead of empty bins, since empty bins qualify as unsaturated bins.
