### ISSUE TITLE
bee contract returned same address to two different Ethereum wallet

### ISSUE THREAD

**Issue by hongikAn** [ethersphere/bee#1425]
#### Summary

Hello
I made two node but they received same chequebook contract address.

1. https://goerli.etherscan.io/tx/0x9a6fe4f3d61facca5a82d775a01f4759ffa1e28d405ce5845a4be5899eb47a3c
2. https://goerli.etherscan.io/tx/0xb73a4400ef14d2bed86e8a06d732d516b424e355c254b20dca8f9f5f0f7a9592
There were in fact THREE checkbook creations at the SAME timestamp.   Here's the third one.
3. https://goerli.etherscan.io/tx/0x88a3fd91515cf930312bb081dcc8b866f3375cbbb9b3929ac7a7d35535043b09

![first address](https://user-images.githubusercontent.com/74804977/111015580-e1475100-83ec-11eb-9fc6-aa7cf21dcff8.png)

![second address](https://user-images.githubusercontent.com/74804977/111015564-c83ea000-83ec-11eb-9df3-4c4290ff4faf.png)

"overlay": "88d63a572233bef0e8183fe0c4cbc4559dd46d2b40b7aee7f9bcfb6e93cb4b19",
  "underlay": [
    "/ip4/172.26.7.181/tcp/1634/p2p/16Uiu2HAmASWUbAX7AWJZK7QrhFSf9WSt1QyzwceUA95tRMSjBv
3L",
    "/ip4/127.0.0.1/tcp/1634/p2p/16Uiu2HAmASWUbAX7AWJZK7QrhFSf9WSt1QyzwceUA95tRMSjBv3L"
,
    "/ip6/2406:da14:ab8:4800:91c9:8a9c:20a0:7de5/tcp/1634/p2p/16Uiu2HAmASWUbAX7AWJZK7Qr
hFSf9WSt1QyzwceUA95tRMSjBv3L",
    "/ip6/::1/tcp/1634/p2p/16Uiu2HAmASWUbAX7AWJZK7QrhFSf9WSt1QyzwceUA95tRMSjBv3L",
    "/ip4/176.34.35.146/tcp/1634/p2p/16Uiu2HAmASWUbAX7AWJZK7QrhFSf9WSt1QyzwceUA95tRMSjB
v3L",
    "/ip4/176.34.35.146/tcp/1634/p2p/16Uiu2HAmASWUbAX7AWJZK7QrhFSf9WSt1QyzwceUA95tRMSjB
v3L"
  ],
  "ethereum": "0xfffba9d8393625fde2f00f6a961f0c5cb710c7d1",
  "public_key": "0218bc225fb5ccb4dbbb84d3d1f578bf3d130425005cc1d3f5b7e135bcb2c62489",
  "pss_public_key": "036d7fcb5b1ceb823fba0df8ba9d10610ac9fa3cb0ae21fe92b0c91144df8fea3a
"
chequebookaddress":"0x7528E78506622F74aA7e077607B76Ffc62759b05
{
  "overlay": "0339923d4f88852e5aad4b703dc54e09ccfb1dd5332e432191cc05a33881c1df",
  "underlay": [
    "/ip4/172.26.15.27/tcp/1634/p2p/16Uiu2HAmQcnQ1v3RV2UQFGqT5Gvd2HX345zW1im8ba67AAnTwP
rp",
    "/ip4/127.0.0.1/tcp/1634/p2p/16Uiu2HAmQcnQ1v3RV2UQFGqT5Gvd2HX345zW1im8ba67AAnTwPrp"
,
    "/ip6/2406:da14:ab8:4800:800b:425a:bd26:b970/tcp/1634/p2p/16Uiu2HAmQcnQ1v3RV2UQFGqT
5Gvd2HX345zW1im8ba67AAnTwPrp",
    "/ip6/::1/tcp/1634/p2p/16Uiu2HAmQcnQ1v3RV2UQFGqT5Gvd2HX345zW1im8ba67AAnTwPrp",
    "/ip4/13.115.163.242/tcp/1634/p2p/16Uiu2HAmQcnQ1v3RV2UQFGqT5Gvd2HX345zW1im8ba67AAnT
wPrp",
    "/ip4/13.115.163.242/tcp/1634/p2p/16Uiu2HAmQcnQ1v3RV2UQFGqT5Gvd2HX345zW1im8ba67AAnT
wPrp"
  ],
  "ethereum": "0x353a2d5ba41ffa6da51d37f901ba0c1453265ff8",
  "public_key": "0290df5b2da051e87e49dd21acd2cf6b3886cecc9bc79d908cca15db36706f3afe",
  "pss_public_key": "03afb96daaf591d896f00b8318de42a2c3166c7b6e40485f2b9bd65f140ba0800d
"
}

chequebookaddress":"0x7528E78506622F74aA7e077607B76Ffc62759b05"

**Comment by ldeffenb** [comment]
I worked with @hongikAn in bee-support when this was noticed.  He is correct in his report that he started 2 new nodes simultaneously on two different machines.  Both nodes deployed their new checkbooks in a single goerli block.  The two nodes subsequently reported a single, shared, checkbook address.

Ethereum addresses:
Node 1: 0xfffba9d8393625fde2f00f6a961f0c5cb710c7d1
Node2: 0x353a2d5ba41ffa6da51d37f901ba0c1453265ff8

Checkbook creation transactions:
0x9a6fe4f3d61facca5a82d775a01f4759ffa1e28d405ce5845a4be5899eb47a3c
0xb73a4400ef14d2bed86e8a06d732d516b424e355c254b20dca8f9f5f0f7a9592

Shared checkbook address: 0x7528E78506622F74aA7e077607B76Ffc62759b05

IP addresses:
Node 1: 172.26.7.181 and 176.34.35.146
Node 2: 172.26.15.27 and 13.115.163.242

If you look at the checkbook contract in etherscan.io, you'll see that TWO 10 gBZZ deposits were initially made, one from each of the nodes.  And from the /chequebook/address queries shown above, both nodes definitely thought they were using that single checkbook address.

Further notice that the checkbook itself shows the first creation transaction ID and that transaction shows that the first node is the From: address which indicates that the first node is the actual "owner" of the checkbook and the second node is the "interloper".

The second creation transaction ID was definitely issued by the second node, but I have no idea what checkbook contract it actually created.  Someone with better knowledge of the contract factory can probably figure this out, but I have no doubt that it remains a non-funded checkbook.

My theory is that whatever mechanism is used to get the contract address back from the factory (possibly relying on Ethereum events) does not provide definitively unique information such that both nodes picked up the first event and adopted that checkbook contract.

Interesting that the third node to deploy a contract in that same block seems to have received and funded it's own checkbook.  Given that this node did the funding into this checkbook, I think it probably got the correct checkbook address back from the deployment.

Ethereum Address: 0x89309062e5e60FB3abf277f97661a2091Ba6717c
Creation Transaction: 0x88a3fd91515cf930312bb081dcc8b866f3375cbbb9b3929ac7a7d35535043b09
Checkbook Address: 0x19681158D4B59358be0926B81476594F01C6E484

I advised @hongikAn to delete and re-initialize the second node since the first node appears to be the proper owner of the resulting checkbook.

https://goerli.etherscan.io/block/4430829 is the goerli bock that contains the three checkbook deployment transactions.  The two that went awry are the bottom two on both the contract and contract internal transactions lists.

**Comment by ralph-pichler** [comment]
It could be that a reorg happened at that block where the order of the two txs was different. There is an issue currently where bee can lock into the wrong chequebook if that happens. we will soon switch to CREATE2 based chequebook deployment which will make this impossible.

**Comment by Eknir** [comment]
Relevant PR in the sw3 repo: https://github.com/ethersphere/swap-swear-and-swindle/pull/120

**Comment by Eknir** [comment]
Thanks for reporting, good advice was given @ldeffenb and indeed, this will be fixed with the upcoming release.
