### ISSUE TITLE
Cashout results in phantom transaction

### ISSUE THREAD

**Issue by pk27734** [ethersphere/bee#1436]
#### Summary
When I run the cashout script with `cashout-all 5`, or `cashout <peer ID>`, the transaction ID is posted but can never be found on etherscan. 

`uncashed cheque for 780396758646d52bfe64df488a0a14ce4168682230622b6555eeaa5bfaf04408 (53896000000000 uncashed)
cashing out cheque for 780396758646d52bfe64df488a0a14ce4168682230622b6555eeaa5bfaf04408 in transaction 0xade67f9757137c42f32ad8674ab45fba2e4500808f0779919fcd96a0acdf1127
`
This occurs when running both a local Nethermind Goerli node as well as using Infura.

#### Steps to reproduce
`./cashout.sh cashout-all 5`

#### Expected behavior
Multiple cashouts occurring in an appropriate timeframe. 

#### Actual behavior
The script is stuck on the first cashout and does not execute any of the following. If I cancel this and start it again, I am losing this cashout/cheque.

**Comment by pk27734** [comment]
After some debugging with @ldeffenb on Discord, it seems that the API responds flaky and gives 500 errors when calling `/chequebook/cashout/<PeerID>`. Every 1 in 7 calls gives proper results, otherwise it's 500. This has been tested using infura.

**Comment by ldeffenb** [comment]
That was a GET on /chequebook/cashout/<PeerID> that was giving intermittent 500 errors:
{
  "message": "cannot get cashout status",
  "code": 500
}
But sometimes it works:
{
  "peer": "7b5f29141c2106c7f3be0b5e61aa0ae7544daeddf3c5f7d98bc0cee8aee50edf",
  "chequebook": "0xa0f8d8fde1a6a95a013643094ac1e36ff1ce490e",
  "cumulativePayout": 180000000000,
  "beneficiary": "0xdf8a7f178c4d06cdc50261f46f7393b2bf1a7931",
  "transactionHash": "0xa5dfffc0939d559da8ef4f359923213ae8a8d264518fa8bfac35333368dbfd13",
  "result": null
}

When we did try a POST of /chequebook/cashout on that same peer, we received a transaction ID, but it was not visible at goerli.etherscan.io.  I'm suspecting that something in the actual cashout can actually generate a transaction ID, but then fail to post it to a non-reliable swap-endpoint that results in these "invisible" transactions.
{
  "transactionHash": "0x975e98366fa76e0d7142cd05aaa7b521b1510611366bf5729f2bdedbccc81686"
}

**Comment by ralph-pichler** [comment]
If you received a hash from the POST endpoint it means the tx was sent to at least one eth node which also confirmed that it was received.  Maybe that eth node did not pass it along. I also saw in the past that the suggested gas price was too low and the tx did not distribute in the network because of that.

As for the 0 value cashouts, this is to be expected if you call the POST endpoint directly (currently). It just tells the bee node to attempt cashing the last cheque, but it does not actually verify if there is any uncashed amount left. (This is so that users can always manually force cashing the last cheque, otherwise there might be some edge-cases where a pending tx (like here) does not confirm and the user would not be able to send new txs). You should always manually verify that there is in fact uncashed amount before calling the POST endpoint. That being said even the cashout script does not behave well if there are still pending txs while cashout-all is called. After the next minor release we will merge the api change from #1402 which has a better a.

**Comment by pk27734** [comment]
@ralph-pichler is it then possible to increase the gas price for a cashout?

**Comment by Eknir** [comment]
Fixed per https://github.com/ethersphere/bee/pull/1402
