### ISSUE TITLE
"Out of Gas" transaction handling?

### ISSUE THREAD

**Issue by ldeffenb** [ethersphere/bee#1450]
#### Summary
With the recent gas price fluctuations on the goerli test network, many of us are accumulating failed cashout transactions due to "out of gas".  Are these transactions reverted internal to bee or do we need to somehow reprocess them as was mentioned in bee-support?

#### Steps to reproduce
Do a bunch of cashouts and you'll likely hit an out-of-gas as the goerli network jumps the price to 20gwei instead of 1.

#### Expected behavior
I would like to believe that the bee node will detect the failed transaction and make the peer cashable again, but having examined the source code, I don't think that is currently the case.

#### Actual behavior
I haven't done a definitive test yet, but I suspect that the peer is no longer cashable until at least another threshold has been reached.  And even then, I'm not certain that the new check will include the settlement from the failed cashout transaction.

The following script was suggested in bee-support as being necessary to get the out-of-gas transactions to be reprocessed.  I can confirm that it lists my failed transactions, but I'm not sure if I can meet the requirement for a "geth compatible" keystore and password for my node's Ethereum account.

https://gist.github.com/syspulse/dd652cce3bf2e1ddc13272ef4e472726

**Comment by ldeffenb** [comment]
Any comment from the developers on what can be done to recover these transactions?

**Comment by kevin486** [comment]
I have many cash transactions went into out-of-gas error,  and desperately need help on this point.

**Comment by Eknir** [comment]
If you can send a cheque with a same peer when you have received `new` cheques, then you will also cash out the old cheques. The reason for this can be found in how cheques are internally implemented (see [sw3](https://github.com/ethersphere/swap-swear-and-swindle/blob/master/contracts/ERC20SimpleSwap.sol#L224)). 

As you can see, what matters is the cumulative amount on the cheque. If you did not cash out a previous cheque, then the chequebook of your peer did not update the `paidout[beneficiary]` mapping, so you will just receive the payout as if the previous transaction did not happen.

While I understand this is a nuisance, we will not work on fixing this now. Especially since there is a way around this.

Thanks for reporting though and please let me know if you need any further explanations (can be here in a comment or PM).
