### ISSUE TITLE
increase open file limit in systemd service file

### ISSUE THREAD

**Issue by jpritikin** [ethersphere/bee#1485]
The 0.5.3 release notes encourage override the default number of open files to 7-12k,

```
## number of open files allowed by database
db-open-files-limit: 10000
```

This will fail if the corresponding systemd limit is also not raised,

```
LimitNOFILE=20000
```

This line should be added to the systemd service file.

**Comment by Eknir** [comment]
Hi there,

This is not a standard configuration and hence, we will not add it to the systemd service file (unless it becomes standard). It does seem to me like something that can be documented. Feel free to make a PR against bee, or at any place where you would expect a comment about this, so that it would help people like you to figure out this configuration by themselves.

Tagging @vandot , so he is aware of this and can approve your PR.

**Comment by Eknir** [comment]
I connect this issue with https://github.com/ethersphere/bee/issues/1559

**Comment by ndcc5** [comment]
Why one is 10,000 and the other is 20,000? Shouldn't they be the same?

**Comment by jpritikin** [comment]
> Why one is 10,000 and the other is 20,000? Shouldn't they be the same?

They could be the same. The constraint is `db-open-files-limit <= LimitNOFILE`

**Comment by acud** [comment]
since every platform has different ways to set the number of open files it is up to the users to find the correct way to change the number of maximum open file a process may have on their operating system. The number of maximum open files must be at least `<db-open-files-limit>+<statestore open files>+<all open tcp connections>`. Since bee uses multiplexed TCP sockets to communicate with peers, this basically means that 1 peer equals one TCP socket file descriptor. so 1000 peers would mean that you would keep another ~1000 (maybe more) file descriptors open for the network sockets. There are also files being kept open by the state store that keeps tabs over the application state (accounting, syncing intervals, peer stat data, and so on)
