### ISSUE TITLE
Wrong default configs used - bee doesn't correctly determine the user running the process.

### ISSUE THREAD

**Issue by cobordism** [ethersphere/bee#1517]
#### Summary
bee uses incorrect default config.

#### Steps to reproduce
```
$ bee printconfig 2>&1 | grep "config"
config: /home/cobordism/.bee.yaml
$ sudo bee printconfig 2>&1 | grep "config"
config: /home/cobordism/.bee.yaml
$ sudo -u bee bee printconfig 2>&1 | grep "config"
config: /home/cobordism/.bee.yaml
$ sudo su
# bee printconfig 2>&1 | grep "config"
config: /root/.bee.yaml
#  sudo -u bee bee printconfig 2>&1 | grep "config"
config: /root/.bee.yaml
```
#### Expected behavior
At the very least, I expect it to use the home directory of the user running the command. 
in other words I expect:
```
$ bee printconfig 2>&1 | grep "config"
config: /home/cobordism/.bee.yaml
$ sudo bee printconfig 2>&1 | grep "config"
config: /root/.bee.yaml
$ sudo -u bee bee printconfig 2>&1 | grep "config"
config: /home/bee/.bee.yaml
```

This also affects the data-dir configuration.

The command never uses the file /etc/bee/bee.yaml unless explicitly given as a cli argument, even though this is the default configuration file in all the docs / guides.

**Comment by Eknir** [comment]
`bee printconfig` returns the configuration in whatever way bee would bee configured if you would write `start` instead of `printConfig`.

If you installed bee as a package, it comes with a specific configuration file that is passed upon starting that package.

Calling `bee printConfig` does not have knowledge of this configuration file unless explicitly mentioned (which you can do by `bee printConfig --config /etc/bee/bee.yaml`).

I don't see that there is wrong behavior here, but perhaps your expectation of what `bee printConfig` would do is different?

**Comment by cobordism** [comment]
> I don't see that there is wrong behavior here

```
sudo -u bee bee printconfig 2>&1 | grep "config"
config: /root/.bee.yaml
```
This means: run as user "bee" the command "bee printconfig", and it comes up with config "/root/.bee.yaml"
