### ISSUE TITLE
Not Found on gateway.ethswarm.org

### ISSUE THREAD

**Issue by hanna-liashchuk** [ethersphere/bee#1534]
#### Summary
I've uploaded a file using `curl -F file=@bee.jpg http://localhost:1633/files` command, result is
`{"reference":"044b15100e2385101b1886a52d33d9a31cd06874cfdf1a9aafde2dc6f82d0471"}
`
But page https://gateway.ethswarm.org/files/044b15100e2385101b1886a52d33d9a31cd06874cfdf1a9aafde2dc6f82d0471 returns not found

#### Steps to reproduce
Upload a file and try to share it via gateway.ethswarm.org
#### Expected behavior
File is available on gateway.ethswarm.org
#### Actual behavior
Not found

**Comment by Eknir** [comment]
Thank you for reporting this. The Swarm network is a multitude of nodes with various latencies and configurations that all need to collaborate with each other. We are currently witnessing a Swarm network size that was never seen before and because of that, we run into situations not previously encountered. Rest assured that we are working on fixing this.

**Comment by Eknir** [comment]
Please let us know if this resolved in v0.6.0!
