### ISSUE TITLE
Increase the open files limit and log a warning if the setting is too low

### ISSUE THREAD

**Issue by filoozom** [ethersphere/bee#1559]
# User story
## Story
As a node operator, I want my node to automatically increase the `--db-open-files-limit` based on the current value of `ulimit -n`, and to log a warning if it's too low, such that my node is more performant or tells me if my configuration isn't optimal.

## Acceptance criteria
If my node is ran with too low `ulimit -n`, I expect a warning to be printed.

If I run my node with `ulimit -n 8192`, I expect the open files limit to automatically be increased, say to 4096.

## Background
We have been talking a lot about performance issues on the Discord, and it seems like increasing the open files limit is a huge factor for nodes to perform better.

We believe that the default limit of `200` is too low, and @agazso suggested to raise the system's `ulimit -n` to something like 65535 (https://discord.com/channels/799027393297514537/810905662375854123/829009098250911754). We also believe that this limit is used by most node operators, and that a lot of nodes are thus quite slow, which could slow the whole network down.

The LevelDB folder contains a lot of files. For my open gateway:

```
$ ls -al ./bee/localstore/ | wc -l
80457
```

I thus set my limit to 131.072, and the limit inside the Docker container to the double of that. This should ensure that every file can be kept open if necessary. I don't know if this is appropriate though.

## Tasks
I guess this should be done by a core developer, but basically:

- Read the limit (https://golang.org/pkg/syscall/#Getrlimit)
- Log a warning if it's too low
- Increase the open file limit to a decently high value

| Task | Assignee |  Done (1), or 0 |
| ------ |------------| -----|

**Comment by ldeffenb** [comment]
bee.yaml/command-line parameter capability added in #1454 supporting the original change done in #1339 

In 0.5.3 users can set a larger-than-default value for the LevelDB open files limit via db-open-files-limit in their bee.yaml file or as --db-open-files-limit on the command line.  Any value can be specified up to the user's default open files soft limit viewable on Ubuntu as "ulimit -Sn".  But don't give the entire soft limit to LevelDB, but save a few 100 for other files and network connections that your node will need.

For instance, if "ulimit -Sn" tells you 1024, then you can use something like db-open-files-limit: 800 or so, probably safely.

**Comment by filoozom** [comment]
To be a bit more exact about actual usage of open file descriptors:

```
lsof -p 303971 2>/dev/null > lsof.txt
cat lsof.txt | grep "protocol: TCP" | wc -l
cat lsof.txt | grep "/home/bee/.bee" | wc -l
cat lsof.txt | grep -v "/home/bee/.bee" | grep -v "protocol: TCP"
```

**Comment by Eknir** [comment]
Relevant comment: https://github.com/ethersphere/bee/issues/1312#issuecomment-818687884

**Comment by acud** [comment]
@filoozom I'm inclined to close this because:
- different platforms will have different ways of setting the number of open files
- this can lead to a spiral of integrations that would have to be maintained
- if the ulimit is too big, swarm can automatically chew up too much of it, masking some bugs and problems (like file descriptor leaks)
I think that printing a warning when the number of max open files is low is valid, but I'd avoid pursuing automating things here. WDYT?

**Comment by filoozom** [comment]
I haven't had much time to run and benchmark bee nodes lately, maybe @ldeffenb has more insight as to if it's still an issue?

Sure, the limit could be too big, but that's why we'd first check how high we can go before updating it. If it's a maintenance nightmare, I think a warning could be enough. Maybe also throw in a link to some documentation?

**Comment by acud** [comment]
I am not even sure how to display the warning, since even getting to the actual limit from the operating system is not trivial and would need different implementations to fetch the data from different platforms

**Comment by ldeffenb** [comment]
> I haven't had much time to run and benchmark bee nodes lately, maybe @ldeffenb has more insight as to if it's still an issue?

Yes, the open files limit is still an issue, at least for me.  I have so far firmly resisted changing the default ulimit on my host OS and just this morning ran into the issue when restarting the screen sessions under which 2 of my mainnet nodes run.  I only noticed I skipped the "ulimit -n 10000" step when monBee and Grafana showed those nodes not attaining their expected 12 depth.

There is a golang package to support adding a dynamic expansion of ulimit, provided that the host OS has a sufficient hard limit.  I haven't looked at using it yet, but it can be found at https://github.com/golang/sys  This is the new (golang 1.4, IIRC) approach to what was previously available as https://pkg.go.dev/syscall#Getrlimit and https://pkg.go.dev/syscall#Setrlimit

I don't know about automatically increasing the open file limit if there is deemed to be a sufficient limit available, but it sure would be nice to have the program automatically try to get an increased open file limit at runtime rather than simply failing to open LevelDB files, log files, and/or network connections.
