### ISSUE TITLE
pushsync: swallow `ErrWantSelf` if closer nodes exist

### ISSUE THREAD

**Issue by acud** [ethersphere/bee#1639]
Currently we might wrongly assume we are the closest one when returning from the `pushToClosest` method, since kademlia might just exhaust the number of known peers closer to a chunk than we are. While this does not mitigate the problem while building the initial topology, we should swallow a potential `ErrWantSelf` in pushsync whenever there is a peer being returned from `ClosestPeer` (i.e. if `ClosestPeer` returns a certain peer then we should swallow the error).

**Comment by ldeffenb** [comment]
But what happens in the case that the known ClosestPeer is having unrecoverable issues unbeknownst to us, like an overdrafted checkbook or insufficient threshold?  In this case, we'll never finish, especially if all of the forwarding nodes also know about this same non-functioning peer.

We need some determination of "close enough" so that a pushsync chunk can be accepted by a node that isn't necessarily "closest", but is "close enough" to store the chunk until the neighborhood pullsync can get it more fully distributed.

But retrying a failing chunk over and over again to the same set of peers is exactly what #1651 is about and what I've observed numerous times in 0.5.3.

**Comment by Eknir** [comment]
> We need some determination of "close enough" so that a pushsync chunk can be accepted by a node that isn't necessarily "closest", but is "close enough" to store the chunk until the neighborhood pullsync can get it more fully distributed.

@acud , could you please clarify if the push sync is always pushing to the closest peer, or just to one peer in the neighborhood? Based on my understanding, if a node is in the neighborhood, it should just accept that chunk return a receipt and redundantly push to others in the neighborhood. However, if we always want to push to the closest, then this can indeed cause a problem if the closest node has problems.

**Comment by ldeffenb** [comment]
My understanding of 0.5.3 behavior is that every node always attempts to push to the closest peer for the chunk's ID, regardless of whether the chunk has actually arrived "in the neighborhood".  And the push-forwarding node won't decide to keep the chunk if there are at least 5 "closer" connected nodes than his own.  ErrWantSelf will only be returned if we run out of closer connected nodes before we run out of pushToClosest retries.

**Comment by aloknerurkar** [comment]
Based on my discussion with @acud it seems like this issue will be handled by a couple of other changes we have/will make.

- #1685 Return ErrNotHealthy from kademlia if we don't have a healthy topology
  This will ensure that we don't wrongly assume that we are the closest node until we have built a healthy kademlia topology. So we will not store the chunk in this case.

- #1653 remember failed traces (checked-in)
  This change was merged today. It adds an LRU cache to remember failed {peer, chunk} requests to prevent peers from retrying unreliable peers. We have also increased the timeout duration to allow more time for the requests to succeed. This should reduce network latency-related errors.

 In the case of a forwarder/originator, if there are peers which are not reliable for a particular chunk, we will not attempt to forward to these peers. Due to which we will try other peers. If there are no more peers and kademlia is healthy, we will return ErrWantSelf and store the chunk. So even if there is a closer node, and it's not reliable, replication will happen.

 If there are closer peers and we attempt to send and fail, we will return ErrNoPush which will prevent the peer from wrongly storing the data.

So once both the above issues are handled, we should be able to close this.
