### ISSUE TITLE
Get info about Bee node on the API

### ISSUE THREAD

**Issue by nugaon** [ethersphere/bee#1668]
# User story

Recently the Bee node can start either as a full node, light client or in gateway mode. Their _active services_ (that you can call and get successful response from, via HTTP API) differ from each other and it is not possible right now to tell about the services of the target node whether those are active or not _from code_ (unless you know which services won't work in a particular mode and you handle the exception in that way, but it is not the best alternative).

## Story

Therefore would be nice to have an endpoint on the Bee API which tells what paths of the node are active and which ones are turned off so that the apps which communicates with bee node(s) could handle properly these differences. 

## Acceptance criteria

`/info` (or with some other name) API EP, which tells information about the Bee node, and one property of this gives back what services are turned off (like `/pin/*` paths) as an array 

## Background

We had to handle somehow in `swarm-cli` the pinning is not available in gateway mode, but we [did not do in a nice way](https://github.com/ethersphere/swarm-cli/issues/97)

## Tasks

| Task | Assignee |  Done (1), or 0 |
| ------ |------------| -----|

**Comment by AuHau** [comment]
Honestly, I am not sure if we need a list of endpoints that are available, but I agree with an endpoint that displays information in what mode the Bee runs as it affects what is available to the user.

Currently, there is "Status" section of endpoints that are exposed on the Debug API. I would maybe suggest having this new endpoint we are talking about, part of the main API as this crucial from user perspective to have this information always available no matter if he has or has not enabled Debug APIs.

**Comment by vojtechsimetka** [comment]
Knowing what mode the Bee runs in is also needed for the Bee Dashboard https://github.com/ethersphere/bee-dashboard/issues/128 .

I agree with @AuHau that having all the available enabled endpoints is not absolutely necessary and knowing the mode is enough. But from a user perspective, having this broken down to "what endpoints work" (as @nugaon suggested) would IMHO be nice and more useful.

**Comment by acud** [comment]
This smells a bit like WSDL by nature. I don't necessarily object to this but this is obviously going to end up with an added maintenance burden on top of complicating the API design. I think that if there's an endpoint that returns the bee version and that we keep a rigorous regime of making sure that the openapi version spec is the same as the bee version then the problem is mostly solved.

With regards to the debug API - from my perspective it should not be used for anything else but development purposes. The fact that it's a functional catch-all for everything which does not make sense to land in the normal API does not mean that this is a desirable situation in the long run. I believe that a lot of the things that are under the debug API should land into the authorized API we've been discussing for a while now (and we need to prioritize in our pipeline). And even when maintaining an authorized API I'm not sure about implementing some sort of WSDL that would be dynamically maintained at runtime. Perhaps generating one from openapi would be the closest and easiest we can get, for now.

**Comment by AuHau** [comment]
@acud agree with you, but at the same time, the API user should be able to determine what to expect from the API prior actually making any requests. As I have already said, I don't think this "WSDL-like" system/endpoint is needed, but having a bee version as you mentioned and some other basic configuration information exposed that affects the behavior of the API like if it is in gateway mode, light-node mode etc is essential. 

Otherwise, we have to do hacks like "lets try to create a tag, and if it fails then most probably the node is in gateway mode", which is not really maintainable in long term as these hack-conditions might change and then we have to find other ways how to deduct this info.
