### ISSUE TITLE
General problem description

### ISSUE THREAD

**Issue by filwu8** [ethersphere/bee#1698]
why？

level=warning msg="get your Goerli ETH and Goerli BZZ now via the bzzaar at https://bzz.ethswarm.org/?transaction=buy&amount=10&slippage=30&receiver=0xbbb70af10a949ce8740696613e95d60df8e5e0ab"

level=warning msg="get your Goerli ETH and Goerli BZZ now via the bzzaar at https://bzz.ethswarm.org/?transaction=buy&amount=10&slippage=30&receiver=0xbbb70af10a949ce8740696613e95d60df8e5e0ab"

level=warning msg="get your Goerli ETH and Goerli BZZ now via the bzzaar at https://bzz.ethswarm.org/?transaction=buy&amount=10&slippage=30&receiver=0xbbb70af10a949ce8740696613e95d60df8e5e0ab"

**Comment by acud** [comment]
this is needed because of the default settings that have a positive chequebook deposit. if you set the swap initial deposit to zero you could potentially start your node without any gETH or gBZZ but it will operate in a limited manner (no fast downloads that trigger cheques and no uploads with postage stamps)
