### ISSUE TITLE
Node initialization has been stuck in the deployment contract phase due to low GAS

### ISSUE THREAD

**Issue by dislikediss** [ethersphere/bee#1782]
Node initialization has been stuck in the deployment contract phase due to low GAS

**Comment by Eknir** [comment]
Hi there, Thanks for trying out Bee! This is caused by the Goerli network, being currently under heavy use. 
This problem is addressed by https://github.com/ethersphere/bee/pull/1773, but ultimately the root cause lies in Goerli, being a free resource and people taking advantage of this.
This will for sure be solved when Swarm goes to mainnet!
