### ISSUE TITLE
An error occurred shortly after the first boot

### ISSUE THREAD

**Issue by AVANT951** [ethersphere/bee#1823]
Upgrade from 0.5.3 to 0.6.0. After the upgrade, an error occurred shortly after the first startup
Before upgrade:
------------------
centos 7.5
bee-clef：0.4.9
bee：0.5.3
------------------
Backup files
-------------------
rm -rf /root/.bee/localstore
cp -rf /root/.bee /root/.beeo
cp -rf /var/lib/bee-clef /var/lib/bee-clefo
cp -rf /var/lib/bee /var/lib/beeo
cp -rf /etc/bee-clef /etc/bee-clefo
cp -rf /etc/bee /etc/beeo
------------------
uninstall
------------------
yum remove bee
yum remove bee-clef
------------------
Re install
------------------
rpm -i bee-clef_ 0.4.12_ amd64.rpm
rpm -i bee_ 0.6.0_ amd64.rpm
------------------
Restore backup
------------------
cp -rf /root/.beeo /root/.bee
cp -rf /var/lib/bee-clefo /var/lib/bee-clef
cp -rf /var/lib/beeo /var/lib/bee
cp -rf /etc/bee-clefo /etc/bee-clef
cp -rf /etc/beeo /etc/bee
-----------------
Run command line parameters
-----------------
. / clear service start (same as version 0.4.9)
bee start --full-node --db-open-files-limit 2000 --verbosity 5 --swap-endpoint  https://goerli.infura.io/v3/ffa35c4cc95f4a38a410f3b66fxxxxxx  --debug-api-enable --clef-signer-enable --clef-signer-endpoint /var/lib/bee-clef/clef.ipc
------------------
Error content
------------------
TRAC[2021-05-21T20:51:35Z] connecting to bootnode /ip4/54.167.196.243/tcp/31305/p2p/16Uiu2HAmEYYKJZzCE9PuBBzncuAaJ3ZSw5hovsepXjF859wDZ6bd 
panic: runtime error: index out of range [16] with length 16
goroutine 149 [running]:
github.com/ethersphere/bee/pkg/puller.(*Puller).recalcPeer(0xc000a42b40, 0x172d398, 0xc000256980, 0xc002300320, 0x20, 0x20, 0x0)
github.com/ethersphere/bee/pkg/puller/puller.go:220 +0x67d
github.com/ethersphere/bee/pkg/puller.(*Puller).manage(0xc000a42b40)
github.com/ethersphere/bee/pkg/puller/puller.go:170 +0x428
created by github.com/ethersphere/bee/pkg/puller.New
github.com/ethersphere/bee/pkg/puller/puller.go:82 +0x2aa

**Comment by ldeffenb** [comment]
I looked at the source code and traced it back to pullsync.go's GetCursors which seems to rely on the other peer's handler to return the proper array size via the pullsync.proto.  The cursor handler further relies on pullstorage.go's Cursors that seems to construct the array with swarm.MaxBins entries which should be fine.

But if a 0.6.* node connects to a 0.5.3 node somehow, then it will receive an Ack response that only contains [16] entries which would definitely cause this error.  And it would be random depending on what peers a node connected to.

In bee-support, it seems that only certain people are seeing this, but they are seeing it fairly reliably shortly after node startup, which means that there may be 0.5.3 in 0.6.0 clothing lurking in certain neighborhoods?

I considered a fix whereby the GetCursors routine could examine the returned Ack array and expand it to [32], or possibly we should test it there and blacklist any peer that returns a size different than our own swarm.MaxBins?

Definitely seems reasonable for the puller to "assume" that it got a properly-sized array from the protocol and fix it in pullsync, not puller so that the return from GetCursors can be trusted.

**Comment by ldeffenb** [comment]
Duplicated (with better titles) at #1827 and #1837

**Comment by cppfuns** [comment]
I hope to be resolved first, a large number of my nodes are waiting to be processed

**Comment by Eknir** [comment]
This should be resolved with the latest release. Please reply on this issue if this is the case (or not).
