### ISSUE TITLE
improve DB performance 

### ISSUE THREAD

**Issue by jmozah** [ethersphere/bee#192]
- bring back badger
- Address initial memory usage so that we can reduce infra costs
- Performance speedups in Iteration
- move stateDB to badgerDB
- Add DB specific metrics
- Add debug api to debug DB related issues

**Comment by mrsimicsak** [comment]
While looking into high disk usage I identified that using leveldb as storage for chunks was likely a large part of the problem due to leveldb's compactions causing chunk data to be repeatedly read and rewritten. Research identified badgerdb as better option so I started working on a version of 0.5.3 that uses badgerdb instead of level db for localstore. Today I discovered that localstore was switched from leveldb to badgerdb and then back again. 

Why was badgerdb abandoned? I want to make sure I'm not heading down a deadend before I invest a bunch of time.

**Comment by jmozah** [comment]
@mrsimicsak  ooh, Its a long story :-).  we felt that `levelDB` was not a super optimal database for Swarms storage and access patterns. but it was getting the job done. We even started writing our own Swarm specific DB (called forky). Then i proposed Badger  and even had a PR for that https://github.com/ethersphere/bee/pull/75. But badger was taking more memory preventing to run many instances in our test cluster. Eventually the team decided to go back to `levelDB` due to lack of time to bring in a new DB and test it. My personal opinion is Badger was definitely more performant in many of my benchmarks and i believe that the memory footprint can be brought down by tweaking the configurations. we simply couldn't get it done among the other important tasks at that time. This was the history behind this issue.
