### ISSUE TITLE
A small suggestion about Blockchain Endpoints

### ISSUE THREAD

**Issue by AVANT951** [ethersphere/bee#1954]
Now and in the known future, we will definitely encounter the situation that the blockchain endpoints specified in the bee configuration will not be available for various reasons.

So, why can't we give an alternate blockchain endpoints or a pool file containing multiple blockchain endpoints in the bee configuration?

When the bee client connects to the current blockchain endpoints, it will automatically switch to the next blockchain endpoints if it times out or makes a certain number of errors.

This method can significantly increase the robustness of swarm network.

**Comment by Eknir** [comment]
Hey,

Thank you for the suggestion. Doing this right would actually be very complex, and is not directly related to the core functionality of Bee. It is for this reason that I would recommend looking into whether there is tooling available that would do this for you.
Such tooling would be, from the Bee perspective, one endpoint, but internally would communicate with multiple endpoints. 

This way, we neatly separate concerns and build software that would also be useful for other projects.

I would suspect that such software already exists, but if it is not, we would be happy to find a way towards developing this.

If you (or anybody else), can report here if such tooling exists or does not, that would be appreciated!

**Comment by Eknir** [comment]
Found a project that would do this: https://github.com/emeraldpay/dshackle

**Comment by acud** [comment]
This is quite complicated as @Eknir says, since having different blockchain endpoints might necessarily mean that the different blockchain nodes you're gonna be falling back to will have a different view of the chain, leading to all sorts of inconsistencies that we would have quite some trouble to support. We generally discourage this approach at the moment and we rely on the assumption that the blockchain backend just works. Certain safeguard can be put in place in order to see that it is still syncing, but even that territory isn't very clear on how to handle correctly without making the whole swarm self-destruct on every hiccup
