### ISSUE TITLE
Can I limit the maximum hard disk usage during operation?

### ISSUE THREAD

**Issue by fenglindubu** [ethersphere/bee#1963]
I understand that the upgrade requires deleting the folder. Is it possible to limit the maximum hard disk usage during the operation? Or, when the program is running, deleting a part of the localstore files will affect the new receipts obtained?

**Comment by acud** [comment]
Hi. It is not possible to limit disk drive usage right now. We are taking active steps to try and improve our storage architecture so that `bee` is more efficient on disk usage. About the second question, I did not quite understand the question. Please use the Discussions feature of the `bee` repo to ask general question, so that others can also learn from the questions asked
