### ISSUE TITLE
integration testing (kademlia+retrieval+pushsync)

### ISSUE THREAD

**Issue by acud** [ethersphere/bee#198]
kademlia connectivity test
- [x] verify that we don't have full connectivity
- [x] verify healthy kademlia:
- - [x] check depth from debug api
- - [x] if depth == 0 - don't do any further checks (not healthy)
- - [x] verify at least 2 peers in each bin which is shallower than depth
- - [x] verify connected to all peers where `po >= depth`

retrieval test:
- [x] bootstrap test in a way that 1 chunk is put on 1 node (or alternatively random set of unique chunks on each node)
- [x] check that node is reachable and chunks are retrievable from all other nodes

push sync test:
- [x] upload a chunk to each node
- [x] verify that the chunk reaches the closest peer using debug api

**Comment by svetomir** [comment]
https://github.com/ethersphere/beekeeper/pull/7

**Comment by janos** [comment]
Hi @svetomir, related to https://github.com/ethersphere/bee/issues/220, could you update the check so that the point `verify at least 2 peers in each bin which is shallower than depth` is changed to `verify at least 1 peer in each bin which is shallower than depth`. Depth calculation is based on empty bins.
