### ISSUE TITLE
PSS Message api request failed

### ISSUE THREAD

**Issue by zhupengxiang** [ethersphere/bee#1988]
I started two nodes, and then connected the two nodes,Use node 2 to send a message to node 1
The response I get is 500 internal server error,How to solve it,thanks

![image](https://user-images.githubusercontent.com/17894209/120755242-4ae48080-c540-11eb-8859-ac241f229c19.png)

**Comment by zhupengxiang** [comment]
Can anyone solve it？

**Comment by acud** [comment]
Hello @zhupengxiang 
Please follow our issue template when opening an issue. There's not enough information here so that we can debug the problem.
Providing more information when describing a problem is essential. If the problem still persists, please reopen a new issue and include the logs from both nodes, as well as all steps to reproduce the problem
