### ISSUE TITLE
why does it stop automatically after running for a period of time?

### ISSUE THREAD

**Issue by Gump-II** [ethersphere/bee#2010]
why does it stop automatically after running for a period of time?

![image](https://user-images.githubusercontent.com/16313834/120946859-7fd71a00-c770-11eb-97dd-2009d24097d9.png)

**Comment by ldeffenb** [comment]
Get a more stable connection to your swap-endpoint.  0.6 monitors the swap-endpoint and will shut down your node if errors are detected.  The postage stamps require this in order to keep track of the currently valid stamps.  The most reliable swap-endpoint you can have is running your own local goerli node.
