### ISSUE TITLE
The environment variable BEE_CORS_ALLOWED_ORIGINS does not work under docker

### ISSUE THREAD

**Issue by super321** [ethersphere/bee#2052]
The environment variable BEE_CORS_ALLOWED_ORIGINS does not work under docker

I tried to modify the command and it only worked after adding --cors-allowed-origins as follows:
command: start --cors-allowed-origins="*"

**Comment by lukerhoads** [comment]
Did you uncomment it in the .env file?

**Comment by super321** [comment]
I confirm that I have uncommented and all other environment variables are in effect

**Comment by lukerhoads** [comment]
I was able to correctly set env variables as long as the file had the "." in the ".env". Also make sure to set it as a slice 
```
BEE_CORS_ALLOWED_ORIGINS=["*"]
```

And make sure you are using compose if you want to easily use the .env file. I think you might be pulling the images from hub, instead of "https://docs.ethswarm.org/docs/installation/docker/#docker-compose". I might be wrong though.

**Comment by Eknir** [comment]
I assume this to be fixed.

**Comment by tmm360** [comment]
This still appear to be an open issue @Eknir

**Comment by mrekucci** [comment]
> This still appear to be an open issue @Eknir, at least from my last tests.

@tmm360 could you please open a new issue and provide as much detail as possible (the template will guide you).

**Comment by tmm360** [comment]
> > This still appear to be an open issue @Eknir, at least from my last tests.
> 
> @tmm360 could you please open a new issue and provide as much detail as possible (the template will guide you).

Yes, I will in next days
