### ISSUE TITLE
No cheque while balance is 20021000000000 with one peer (exceed the threshold) ！ Same  problem on another 10 nodes!

### ISSUE THREAD

**Issue by fanyongpeng** [ethersphere/bee#2075]
#### Summary

My nodes started for 1 week, I found some balance already exceed the  threshold 10^13, but still no cheque.  NONE of all my nodes !!!

#### Steps to reproduce

Pick one sample 

- My node address: 

`{
  "overlay": "1a87ac2ed76931a3e2e8b60c2fe0b30cf8d02f82ed4c85218845fbbb5583c1fe",
  "underlay": [
    "/ip4/172.18.0.6/tcp/1634/p2p/16Uiu2HAmDHfEJwevt3ba3t6VbXHiv2qwhXj596jwFwQoaXsJmB6M",
    "/ip4/127.0.0.1/tcp/1634/p2p/16Uiu2HAmDHfEJwevt3ba3t6VbXHiv2qwhXj596jwFwQoaXsJmB6M",
    "/ip4/54.221.249.26/tcp/13634/p2p/16Uiu2HAmDHfEJwevt3ba3t6VbXHiv2qwhXj596jwFwQoaXsJmB6M",
    "/ip4/54.221.249.26/tcp/13634/p2p/16Uiu2HAmDHfEJwevt3ba3t6VbXHiv2qwhXj596jwFwQoaXsJmB6M"
  ],
  "ethereum": "0x075bf69405010ff953c14b96167fd22120366d8d",
  "publicKey": "02eaaf1b1b9442b649a0dda442688e5fe08ae21b25ff7c39d5120be3b312c7abd3",
  "pssPublicKey": "039a69d5bcfa4d75d2161cfb2d545f199c975139d1ce22d362117a95096959a13f"
}`

- Request the /balances ,one peer already exceed the  10^13
`     {
      "peer": "11d6520b95f67b718049fedcdd4be9f880932ee91b4aef98db86f287e975ca0a",
      "balance": 20023000000000
    }`
  

- Request the /chequebook/cheque, it's empty
  `{
  "lastcheques": []
}`

- Request the /settlements

`{
  "totalReceived": 0,
  "totalSent": 0,
  "settlements": []
}`

- Look up the log
`time="2021-06-12T18:52:48Z" level=info msg="attempting to connect to peer \"11d6520b95f67b718049fedcdd4be9f880932ee91b4aef98db86f287e975ca0a\""
time="2021-06-12T18:52:55Z" level=debug msg="could not connect to peer \"11d6520b95f67b718049fedcdd4be9f880932ee91b4aef98db86f287e975ca0a\": handshake: write ack message: context deadline exceeded"
time="2021-06-12T18:52:55Z" level=debug msg="kademlia pruned peer from address book \"11d6520b95f67b718049fedcdd4be9f880932ee91b4aef98db86f287e975ca0a\""
time="2021-06-12T18:52:56Z" level=debug msg="kademlia: peer not reachable from kademlia \"[Underlay: /ip4/142.202.242.201/tcp/1634/p2p/16Uiu2HAmErLVri7NRc4XZ4eDVPNkfQWUiJo76WaQd4SYca55MUnt, Overlay 11d6520b95f67b718049fedcdd4be9f880932ee91b4aef98db86f287e975ca0a, Signature b9772eb2b5fd525fae64dda806756c6b0e78075d2e56cff56d970efb2c722fb5790b18b4f0c624552b1b20ad469a5a76217d4bc69a3b4950cd4288a797304a631c]\": handshake: write ack message: context deadline exceeded"`

logs show that peer not reachable

So i try to request this peer's debug api, its ok
![image](https://user-images.githubusercontent.com/5253188/121833068-1cb02f00-ccfe-11eb-8013-5477130cb0ec.png)

![Uploading image.png…]()

telnet port 1634, Unable to connect to remote host: Connection refused

- Try connect 
curl -X POST 172.32.24.77:13635/connect/ip4/162.214.182.249/tcp/1634/p2p/16Uiu2HAmQ1iXwoJtPHAXxxuVRU4SqZ69Jh7XXywrp8ZcRnU3aaWj
 `{"message":"failed to dial 16Uiu2HAmQ1iXwoJtPHAXxxuVRU4SqZ69Jh7XXywrp8ZcRnU3aaWj: all dials failed\n  * [/ip4/162.214.182.249/tcp/1634] failed to negotiate security protocol: context deadline exceeded","code":500}`

#### Expected behavior

Should give me cheque

#### Actual behavior

Balance is high , but no cheque.  Same things happen in 10 nodes, none of any node received cheque. Is that all peer can not connect but debug api still ok ? I don't know what happen!

**Comment by fanyongpeng** [comment]
I try another peer, port 1634 is ok

![image](https://user-images.githubusercontent.com/5253188/121834211-c395ca80-cd00-11eb-9695-cdd9e1bb8062.png)

But try connect by debug api :
curl -X POST localhost:13635/connect/ip4/142.202.243.79/tcp/1634/p2p/16Uiu2HAmP9fKHnJzXYjShCWxPgLQrJR7mKy46B63EQYVpX7PrmSS
![image](https://user-images.githubusercontent.com/5253188/121834275-e88a3d80-cd00-11eb-9bc2-fa14fee0978a.png)

`{"message":"handshake: read synack message: context deadline exceeded","code":500}`

**Comment by fanyongpeng** [comment]
I try to restart my node, 142.202.243.79 is connected , but still no cheque

**Comment by ldeffenb** [comment]
This was explained by Eknir in the #bee-support channel of the official Discord server on June 10th.  He posted:

https://discordapp.com/channels/799027393297514537/810905662375854123/852525187772841994

Dear node operators,

As you have experienced, Bee v0.6 does not distribute cheques. The reason why this does not happen is because of a new feature that was introduced recently: time-based settlements.

With time-based settlements, nodes gradually forgive each other their debt by time. This allows for major improvements in user-experience (send your friends a Swarm link, which they can open without first deploying a chequebook) and security (only originator nodes are required to pay). Simultaneously, the main reasons for SWAP (spam protection and motivating nodes to collaborate) are preserved.

The good-old monetary settlement (with cheques) is still there and is activated automatically when the time-based credits are not sufficient--ensuring a snappy experience for those willing to pay, while keeping Swarm free for small requests.

Now, the reason why you don't get cheques is because the rate at which nodes give each other free bandwidth per time was initialized too high, compared to the speed at which swarm uploads and downloads.

A blog post is in the making, detailing all you need to know about the end of the airdrop and the upcoming soft launch of the network.

Work is ongoing to improve this situation on the testnet. Stay tuned!

With love,
