### ISSUE TITLE
connection aborted by the software on main machine

### ISSUE THREAD

**Issue by hhenrry501** [ethersphere/bee#2077]
I got these errors since Jun 12, before that the node was running perfectly fine. 
don't know what happened and wonder how to find out which software was interfering with bee node.
I got 7700k with 16gb ram and 1T ssd. 
I am also running Chia but only use 4 threads to plot.

level=error msg="failed syncing event listener, shutting down node err: read tcp 192.168.3.100:51074->54.204.131.149:443: wsarecv: An established connection was aborted by the software in your host machine."

The node will shut down after few minutes now.

**Comment by hhenrry501** [comment]
i only less than 10k requests/day, so there should not be any problem with my georli endpoint api ?

**Comment by Eknir** [comment]
Hey, this is a problem with your Goerli endpoint. Your Bee node shuts down to protect issues on your node and for the network stability. 
Please inspect your Goerli node and try again if you think you found the source of the problem. Running your own Goerli node is most stable!

**Comment by ldeffenb** [comment]
Get a more stable connection to your swap-endpoint.  0.6 monitors the swap-endpoint and will shut down your node if errors are detected.  The postage stamps require this in order to keep track of the currently valid stamps.  The most reliable swap-endpoint you can have is running your own local goerli node.
