### ISSUE TITLE
Gas estimations don't work on xDAI

### ISSUE THREAD

**Issue by Eknir** [ethersphere/bee#2079]

**Comment by ldeffenb** [comment]
Actually a hint that might help.  I saw that xdai only supports OpenEthereum and Nethermind clients.  But the Nethermind client only ever reports 20gwei as the gas price.  A few months ago, I tracked this down to a "ToDo" in the source code that simply returns a constant.  Nethermind has apparently not yet implemented the gas price estimation.

So it may not be "xdai" that doesn't support gas pricing, but it may be related to specifically which service you connect your swap-endpoint to.

**Comment by ldeffenb** [comment]
https://github.com/NethermindEth/nethermind/blob/be95ee2c33979513c594248a7ff01be47cff2ca9/src/Nethermind/Nethermind.JsonRpc/Modules/Eth/EthRpcModule.cs#L143

**Comment by ralph-pichler** [comment]
This is specifically related to gas estimation when the xbzz token is used. it should estimate around 80000 for deposits which is what openethereum does, but nethermind estimate over 9000000 (more than 100 times too high). We will hardcode the gas limits for all transactions for now (unless overridden with the corresponding header).

**Comment by ldeffenb** [comment]
My apologies.  I misread the title as "gas Price" not "gas Estimation", but since bee also looks up the gasPrice from the swap-endpoint, you will eventually run into this on xdai I suspect.  I also believe this nethermind ToDo is why https://stats.goerli.net/ periodically flashes 20gwei as a gasPrice for a block or two even when the gas price is nowhere near 20.   Unfortunately right now is not a good example of that as the stable gasPrice is 21gwie so the 20 won't be as noticeable.
