### ISSUE TITLE
Reg: Insufficient ETH message in Bee client

### ISSUE THREAD

**Issue by smsaravanakumar** [ethersphere/bee#2090]
![bee-client-ethereum-2](https://user-images.githubusercontent.com/19745532/122009544-d202e580-cdd7-11eb-97c3-a8f0cb05b405.jpg)
![bee-client-ethereum-1 gBzz](https://user-images.githubusercontent.com/19745532/122009572-d7603000-cdd7-11eb-9a42-81e2446ead33.jpg)

I am having 1 gBzz  ; My bee client shows there is no sufficient  balance for ETH.

Can anyone help me to solve this.

Advanced thanks

**Comment by Eknir** [comment]
Hi there, thanks for trying out Bee. Your node needs ETH to pay for the transaction costs of the Ethereum network. In the future, please ask such questions in our Discord (referenced on the Swarm website).

**Comment by ldeffenb** [comment]
And the reason is simple.  1gETH is insufficient based on the transaction cost forecasting built into 0.6.2 coupled with the high gas prices in the goerli network.  If this happens again, please capture the current gas price from https://stats.goerli.net/ ignoring any 20gwei because they are likely bogus from Nethermind which returns a hard-coded 20gwei all the time.
