### ISSUE TITLE
Abnormal exit during operation

### ISSUE THREAD

**Issue by oneusdt** [ethersphere/bee#2106]
The error message is as follows

time="2021-06-16T17:47:05+08:00" level=warning msg="puller shutting down with running goroutines"
time="2021-06-16T17:47:05+08:00" level=info msg="kademlia shutting down"
time="2021-06-16T17:47:05+08:00" level=info msg="kademlia persisting peer metrics"

**Comment by ldeffenb** [comment]
Look further back in the logs and I suspect you'll find an error monitoring the blockchain indicating an issue with your swap-endpoint.  0.6 monitors the swap-endpoint and will shut down your node if errors are detected.  The postage stamps require this in order to keep track of the currently valid stamps.  The most reliable swap-endpoint you can have is running your own local goerli node.
