### ISSUE TITLE
Supplied content type is not allowed. Content-Type: application/json is required ?

### ISSUE THREAD

**Issue by twodogegg** [ethersphere/bee#2205]
When I call http://localhost:1633/stamps/100/17, it returns "Supplied content type is not allowed. Content-Type: application/json is required" ", so I called "postman" and returned "{
     "jsonrpc": "2.0",
     "error": {
         "code": -32700,
         "message": "Parse error"
     },
     "id": null
}"
I don't know what is going on

**Comment by Eknir** [comment]
Hi there, this does currently not give us sufficient information to reproduce or otherwise find out what the problem is. Could you please answer:

- What bee version are you running
- What configuration do you use
- What exact steps did you perform on your Bee node before you got this error?
- Does it happen consistently, or did it only happens once?
- What do the logs of your Bee node say?
