### ISSUE TITLE
Receiving 404 when accessing encrypted chunks without the key

### ISSUE THREAD

**Issue by Cafe137** [ethersphere/bee#2215]
I uploaded a text file with encryption and got the address correctly:

```
http://localhost:1633/bzz/ae67248b1d0ce42a146daae63790e9e85cddf5162574f7772cec81993ccf93ba0704b362c59423e135716fa1405689d66760cc29c8488ebb32fe07cdb60f7381
```

I verified it is the original text file.

However, when removing the last 64 characters, I expect to see junk/encrypted content, but is a `404` actually:

```
curl http://localhost:1633/bzz/ae67248b1d0ce42a146daae63790e9e85cddf5162574f7772cec81993ccf93ba/
{"message":"Not Found","code":404}
```

**Comment by mrekucci** [comment]
@Cafe137 I'm not sure which endpoint are you trying to access, since we have two for `bzz` GET:

1) [`/bzz/{reference}`](https://github.com/ethersphere/bee/blob/master/openapi/Swarm.yaml#L232) (notice that there is no trailing slash)
2) [`/bzz/{reference}/{path}`](https://github.com/ethersphere/bee/blob/master/openapi/Swarm.yaml#L286) (notice that after the slash a path is required)

So accessing `/bzz/{reference}/` returns correctly `404`.
