### ISSUE TITLE
Chequebook factory: 0xc2d5a532cf69aa9a1378737d8ccdef884b6e7420 What is the code of the contract？

### ISSUE THREAD

**Issue by oneusdt** [ethersphere/bee#2381]
Chequebook factory: 0xc2d5a532cf69aa9a1378737d8ccdef884b6e7420 What is the code of the contract？

**Comment by mfw78** [comment]
It seems that for this, you're referring to the ChequeBookFactory contract that's been deployed to xDai Chain. For exploring xDai chain, please refer to https://www.blockscout.com/.

Therefore, you can see the deploy contract at https://blockscout.com/xdai/mainnet/address/0xC2d5A532cf69AA9A1378737D8ccDEF884B6E7420/contracts. I do note however that the contract source code hasn't been uploaded / verified.

@significance Not sure who to refer this to for verification on blockscout.com?

**Comment by ralph-pichler** [comment]
the source code is at https://github.com/ethersphere/swap-swear-and-swindle/blob/master/contracts/SimpleSwapFactory.sol

unfortunately verification does not work. flattened verification does not work most likely because of the abicoder pragma in some files and the more advanced verification does not work due to an internal server error on blockscouts side.
