### ISSUE TITLE
alway shutting down after update new version of bee .

### ISSUE THREAD

**Issue by sonygod** [ethersphere/bee#2398]
here is log 

```
time="2021-08-06T06:31:08Z" level=info msg="kademlia shutting down"
time="2021-08-06T06:31:08Z" level=info msg="kademlia persisting peer metrics"
```

system: ubuntu 18.0.4

bee:1.1.0-rc1-657c723f 

endpoint: nethermind fast mode

I use native bee instead of docker compose , use diff port to launght diff bee   like bee1 bee2...etc.
there is no error use 1.0,pre version
my nethermind is locate my local host. and open net 0.0.0.0  port 8545 8546

**Comment by acud** [comment]
Hi @sonygod,

Please follow our issue template when opening an issue. it is crucial you provide us with as much information as possible so that we could try to find the problem. Please provide the configuration you're running bee with: configuration files, CLI flags, etc.
When providing logs please provide as many log lines as possible. It is very difficult to spot a problem by looking at 2 log lines.

With regards to your problem, please make sure that:
- your timezone settings are correct
- your local time is correct
- your nethermind node is fully _synced_

if you still experience the same problem, please open a new issue with as much possible information so that we could try to solve the problem.
