### ISSUE TITLE
Isn't possible to upload a file with documented way

### ISSUE THREAD

**Issue by IgorShadurin** [ethersphere/bee#2434]
#### Summary
Isn't possible to upload a file with documented way

#### Steps to reproduce
1 - Open docs at https://docs.ethswarm.org/docs/access-the-swarm/upload-and-download
2 - Modify upload command `curl -H "Swarm-Postage-Batch-Id: 78a26be9b42317fe6f0cbea3e47cbd0cf34f533db4e9c91cf92be40eb2968264" -F file=@bee.jpg http://localhost:1633/bzz` with my own params `curl -H "Swarm-Postage-Batch-Id: 94da935ef87bd5c2482207f65b3a7308886b354b57338e5aed82496459476e15" -F file=@video.mp4 http://pi.local:1633/bzz`
3 - Run it and get error: `{"message":"could not store directory","code":500}`

#### Expected behavior
Get success message

#### Actual behavior
Get error about directory (but file uploaded)

**Comment by mrekucci** [comment]
Thanks for the report. Could you upload here the logs from when it happened?

**Comment by aloknerurkar** [comment]
This is not the correct way to upload file. `-F` is used for multipart form upload. By default, the Multipart form upload will default to uploading a collection. The request above fails because for forms, you will need to supply Content-Type header for each form file and this is not the correct way to do that. This is already documented in the [API docs](https://docs.ethswarm.org/api/#tag/File) as well.

The documentation link you have added has the following:
`curl --data-binary @bee.jpg  -H "Swarm-Postage-Batch-Id: 78a26be9b42317fe6f0cbea3e47cbd0cf34f533db4e9c91cf92be40eb2968264" -H "Content-Type: video/jpg" "http://localhost:1633/bzz?name=bee.jpg"`

This is the correct way to upload single file.
