### ISSUE TITLE
Feedback on README.md

### ISSUE THREAD

**Issue by crtahlin** [ethersphere/bee#244]
A couple of remarks that might be or might not bee relevant:
- maybe prerequisites should be mentioned (make, golang)
In my case `sudo apt install make golang`
- the readme is written for linux/unix based system? (will not work on Windows I suppose)
- the command `curl localhost:6062/addresses` returns a `Failed to connect to localhost port 6060: Connection refused`. The same for port `6060`. Not sure if something is not working or maybe a firewall issue ...
Request to port `7070` returns a `Received HTTP/0.9 when not allowed`.
Not sure if this is expected behavior at this point or not.
Request to port `8080` does return a JSON, although `{"message":"Not Found","code":404}`.

**Comment by janos** [comment]
Thanks, Crt.

> A couple of remarks that might be or might not bee relevant:
> 
> * maybe prerequisites should be mentioned (make, golang)
>   In my case `sudo apt install make golang`

Will be added, good point.

> * the readme is written for linux/unix based system? (will not work on Windows I suppose)

Yes, only for unix like systems. We should have windows related notes, of course. I just do not have a windows machine, so it is lacking.

> * the command `curl localhost:6062/addresses` returns a `Failed to connect to localhost port 6060: Connection refused`. The same for port `6060`. Not sure if something is not working or maybe a firewall issue ...

This needs to be explained a bit better, I see now. Debug API has to be enabled explicitly with --enable-debug-api flag for port 6060. There are some notes on that but not clear for the whole document.

>   Request to port `7070` returns a `Received HTTP/0.9 when not allowed`.
>   Not sure if this is expected behavior at this point or not.

This is expected behaviour as 7070 is for libp2p protocol, not for user interaction.

>   Request to port `8080` does return a JSON, although `{"message":"Not Found","code":404}`.

We have just talked about the simple web page to upload and download files (like swarm has, but maybe simpler) for the alpha release. This would replace the 404 response. We may have something else, but certainly 404 should be changed to something meaningful.
