### ISSUE TITLE
Postage blockchain operations should return transaction hash

### ISSUE THREAD

**Issue by AuHau** [ethersphere/bee#2595]
#### Problem

Till 1.2 release the postage batch API had only one blockchain operation - creation of batch. You introduced the flag `usable` in the batch listing to track when this creation has enough confirmations and the user can use it for Bee operations.

Now with the new dilute and topup endpoints, there are new endpoints that create blockchain operation that again needs to wait for certain confirmations before it is propagated to Bee state. But currently, there is no way how to say when that happens as the `usable` flag is not really applicable for this case.

#### Proposed solution

Let all API calls that create blockchain transactions return transaction hash (among other things you find necessary). This is already the case for things like chequebook cashout and other things, but the Postage API does not follow this.

There is the Debug API endpoint `/transactions` that then the user can track for pending transactions and see when the transaction is processed.

**Comment by AuHau** [comment]
Hmm so I might have been wrong about my reasoning here. It seems that you block the API call until the underlying blockchain call is pronounced as confirmed. Is that correct?

**Comment by acud** [comment]
@AuHau afaik the API won't block until sufficient confirmations are received in those cases, but knowing whether the change has been propagated to `bee` is easily monitored by polling the batch via the `stamps` endpoint. Once the transaction is mined and the block is propagated, we pick up the event and update the stamp issuer with the correct values. So when you top-up you'll be looking for a value increase on the batch value, and when you dilute you'll be looking for a value change in the batch depth. This was a conscious design decision as it simplifies a lot of the design handling this flow (and this is also why the api returns a `202 Accepted` rather than a `200 OK`)
