### ISSUE TITLE
Upload: Having a slash `/` in `website-index-document` yields 500 instead of 400

### ISSUE THREAD

**Issue by Cafe137** [ethersphere/bee#2661]
This could be a 400 Bad Request instead, and the error message from the logs ("err: index document suffix must not include slash character") could appear in the response.

Also, when it is set to a nonexistent file, the response is 200 OK. This may be fine, more of a design choice.

**Comment by vojtechsimetka** [comment]
I was wondering, why is the `/` in `index-document` disallowed? This means that the index file can not be nested in some sub directory which I consider significant limitation.

Is this so this to protect the users who otherwise could upload some website in a subfolder (e.g. `builld`), set the `index-document` to `build/index.html` which however would fail to load its resources because it would be served from `bzz/<some_hash>/` and look for relative resources in `/` and note `build/`?

**Comment by ldeffenb** [comment]
I suspect the issue results from the way in which the website-index-document is resolved and retrieved.  IIRC, it doesn't redirect to the referenced document, but attempts to resolve it directly from the root node of the manifest or something like that.

**Comment by agazso** [comment]
The specification is that the `website-index-document` cannot start with slash, but can contain slash at a later position.

It also needs to be validated when downloading with the `/bzz` endpoint.
