### ISSUE TITLE
Bee gossips and tries to connect to private IPs

### ISSUE THREAD

**Issue by vandot** [ethersphere/bee#2698]
### Context 
Bee Mainnet 1.4.0

### Summary
Somehow bee gossips private IP's and nodes that are not on that local network tries to connect to them and some providers see it as a port scanning attempt, bee tries to connect to a large number of private IP's and port 1634

### Expected behavior
Private IP's shouldn't be gossiped or bee shouldn't connect to them if not on that private network

### Actual behavior
Bee tries to connect to all private IP's that are not existing in that network

### Possible solution
Maybe, just maybe problem lies [here](https://github.com/ethersphere/bee/blob/master/pkg/p2p/libp2p/upnp.go#L34)

**Comment by aloknerurkar** [comment]
@vandot Going through the code and also after running the node, it seems like we should be doing the right thing.

The problem you mentioned, is actually correct behavior. This is meant to handle port no. mismatches due to outgoing and incoming connections. 

Also, we have specific checks which prevent these addresses from getting gossiped. By default, it should not gossip the private IPs. unless you set the option `--allow-private-cidrs`. Was this set by any chance?

Can we get some more information from the nodes? If possible have a setup we can debug?

**Comment by aloknerurkar** [comment]
@vandot I have created a branch [privateIPGossip]() with additional logging messages. If there is some issue on our side these logs would help us identify it.

Can we run this image on the nodes? The branch is based on the current master. I hope that is not a problem. It will generate a lot of extra logs but we only need the logs from the first 15 mins after the nodes are loaded with this image. This is when most of the nodes connect to each other and exchange their addresses.

**Comment by darkobas** [comment]
This still occurred to me in September.  I don't change the default of --allow-private-cidrs. I think it happens when either connectivity or blockchain is disrupted. I mitigated this with firewall rules on kubernetes but it still happens on docker as docker will always put it self first in fw chain.
They had a similar issue on lighthouse if that's of any help:
https://github.com/sigp/lighthouse/issues/3032

**Comment by plur9** [comment]
Bringing this again to @istae @aloknerurkar attention. Our node operators received a warning from Hetzner where majority of our network is running. We need a plan.

**Comment by istae** [comment]
@mrekucci @aloknerurkar
I wonder if this can be fixed by removing the `isPeerPublic` check?
