### ISSUE TITLE
Reroute root path to reference path when serving website files

### ISSUE THREAD

**Issue by giraffekey** [ethersphere/bee#2749]
#### Summary
`<script src="/index.js"><script>` breaks websites as it requests the JavaScript from `{gateway}/index.js` rather than `{gateway}/bzz/{reference}/index.js`. Rerouting requests that originate from `{gateway}/bzz/{reference}` or `{gateway}/bzz/{reference}/{index}` to the correct location of the file would fix this.

#### Motivation
`"./index.js"` and `"index.js"` will work but not `"/index.js"`. If the path is automatically generated or embedded in the page site deployers may be required to experiment with their build tool just to solve this specific issue, which may be inconvenient if Swarm is not the only place the site is hosted on or the repository for the website is not owned by the deployer.

#### Implementation
The API would listen for `{gateway}/{file}` requests. If this request would return a 404 and the origin of the request is `{gateway}/bzz/{reference}`, then the API would return the results for `{gateway}/bzz/{reference}/{file}`.

Alternatively, adding support for subdomains such as `{reference}.gateway.ethswarm.org` would fix this. Skynet and Handshake gateways have this feature.

#### Drawbacks
It may break the uniformity of the API. It's an exception made for a situational minor annoyance. Code like `<script src="/bzz"></script>` would have unclear behavior.

**Comment by agazso** [comment]
Just saying that the solution for this is using the bzz.link gateway for this. It serves websites under `https://<swarm-reference>.bzz.link`, where `swarm-reference` is the reference returned from Swarm but encoded in a cid format, because the maximum length of a subdomain can only be 63 characters, whereas a swarm reference is 64 characters.

Here is a tool to convert between the different references: https://bah5acgza33susxvxfdcreafjdx6ifbz5xxksu2g2ywwbnqfg4glc7n4syugq.bzz.link

Support for bzz.links are built in the [gateway UI ](https://gateway.ethswarm.org), in the [Bee Dashboard](https://github.com/ethersphere/bee-dashboard) and in [Swarm CLI](https://github.com/ethersphere/swarm-cli). There is also a [JS library](https://github.com/ethersphere/swarm-cid-js) for converting references.
