### ISSUE TITLE
race detector fails ocassionally

### ISSUE THREAD

**Issue by notanatol** [ethersphere/bee#2856]
```
=== RUN   TestWithDisconnectStreams
    connections_test.go:902: expected stream reset error, got send headers: read message: context deadline exceeded
--- FAIL: TestWithDisconnectStreams (16.13s)
FAIL
FAIL	github.com/ethersphere/bee/pkg/p2p/libp2p	172.765s
```
[failing PR step](https://github.com/ethersphere/bee/runs/5638043575?check_suite_focus=true)

**Comment by dis-robins** [comment]
Hi @notanatol,

I had a quick look at this. Github actions seems to be running the tests very slowly. TestWithDisconnectStreams taking approx. 16 secs opposed to approx 1.5 secs locally. Actually, 1.5 secs locally isn't so quick either.

Checked the origin of the timeout/deadline error message and it seems to be in the `sendHeaders` function from `headers.go` (in the`p2p/libp2p` package) and `senderHeaders` is called by `NewStream` in the test. The error is reproducible if the context timeout is reduced to micro-secs on a mbp. btw, i'm a little puzzled why the mbp test run only reproduces a failing test on a micro-seconds deadline rather than milli-seconds but imagine a deeper look at the code might explain it.

Assuming `sendHeaders` is the source of the error (and not a red herring), not sure what it is about the Github actions execution that might be causing a greater than 10sec delay such that the context deadline is exceeded. Guessing just the amount of work that's being done on low-spec processors and the likely resolution might be to increase the timeout rather than improve the github performance.

**Comment by notanatol** [comment]
> Hi @notanatol,
> 
> I had a quick look at this. Github actions seems to be running the tests very slowly. TestWithDisconnectStreams taking approx. 16 secs opposed to approx 1.5 secs locally. Actually, 1.5 secs locally isn't so quick either.
> 
> Checked the origin of the timeout/deadline error message and it seems to be in the `sendHeaders` function from `headers.go` (in the`p2p/libp2p` package) and `senderHeaders` is called by `NewStream` in the test. The error is reproducible if the context timeout is reduced to micro-secs on a mbp. btw, i'm a little puzzled why the mbp test run only reproduces a failing test on a micro-seconds deadline rather than milli-seconds but imagine a deeper look at the code might explain it.
> 
> Assuming `sendHeaders` is the source of the error (and not a red herring), not sure what it is about the Github actions execution that might be causing a greater than 10sec delay such that the context deadline is exceeded. Guessing just the amount of work that's being done on low-spec processors and the likely resolution might be to increase the timeout rather than improve the github performance.

Thank you for looking into this.

@janos how should we tackle this one? by fiddling with the timeout or a code fix is more appropriate?
