### ISSUE TITLE
Content type missing in multipart post

### ISSUE THREAD

**Issue by mshearer0** [ethersphere/bee#2864]
Hi, i'm trying to POST formData to Bee from a Vue app and i get: 

DEBU[2022-03-25T19:28:50Z] bzz upload dir: store dir err: read tar stream: content-type missing 
ERRO[2022-03-25T19:28:50Z] bzz upload dir: store dir   

const response = await this.$http.post(`${this.$config.BZZ_ENDPOINT}/bzz`, formData, {headers: {'swarm-postage
-batch-id':'xxx','Content-Type':'multipart/form-data'}})

Any help appreciated.

**Comment by agazso** [comment]
The `/bzz` endpoint expects either a tar file to be uploaded or a multipart form. When you use the `multipart/form-data` each part of the multipart has to be a file with the `content-type` header set correctly.

If you are using Javascript it may be easier to use the https://github.com/ethersphere/bee-js library which provides convenient wrapper functions around the API so that you don't have to deal with details like this.

**Comment by mshearer0** [comment]
Thanks. I understand the browser should set the content types automatically when using a multipart form but when I look at the POST it doesn’t seem to - can I force this?

**Comment by agazso** [comment]
The `formData` variable that you pass for uploading needs to be created properly, something like this:

```javascript
const formData = new FormData()
formData.append("filename", file) 
```
The `file` object must be of type [File](https://developer.mozilla.org/en-US/docs/Web/API/File). Then its `type` property is used as the mime type. Usually in a form you can get it from the list of selected files from `event.target.files` as an array.

However this is not really related to Bee itself, but rather how to correctly create `FormData` objects in Javascript. In order to avoid issues like this I highly recommend to use the [bee-js](https://github.com/ethersphere/bee-js) library I mentioned above.
