### ISSUE TITLE
Bee package on Linux prints out goerli testnet instructions

### ISSUE THREAD

**Issue by agazso** [ethersphere/bee#2935]
### Context
Bee package prints out goerli testnet instructions when installed on Linux. Since #2859 the defaults are using the mainnet, which in this case refers to the Gnosis chain. Therefore instead of suggesting `Infura` it would be better to suggest `getblock.io`.

### Steps to reproduce
Currently message printed into terminal after you install deb or rpm package is this:
```
Logs:   journalctl -f -u bee.service
Config: /etc/bee/bee.yaml

Bee requires an Ethereum endpoint to function. By default is using ws://localhost:8546 ethereum endpoint.
If needed obtain a free Infura account and set:
swap-endpoint: wss://goerli.infura.io/ws/v3/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
It is recommended to use external signer with bee.
Check documentation for more info:
- SWAP https://docs.ethswarm.org/docs/installation/manual#swap-bandwidth-incentives
- External signer https://docs.ethswarm.org/docs/installation/bee-clef

After you finish configuration run 'sudo bee-get-addr'.
```

**Comment by vandot** [comment]
This message is printed for all packaged options for bee [deb](https://github.com/ethersphere/bee/blob/master/packaging/deb/postinst#L10), [rpm](https://github.com/ethersphere/bee/blob/master/packaging/rpm/post#L9), both [brews](https://github.com/ethersphere/bee/blob/master/.goreleaser.yml#L283) (amd64 and arm64) and [scoop](https://github.com/ethersphere/bee/blob/master/.goreleaser.yml#L265)
It's not only about infura, maybe we should address the whole message and refresh it

**Comment by significance** [comment]
here's an updated version for mainnet since this is now the default it makes sense to print only this.

i taken the same approach for bee-get-addr which i guess can arguably access the config and as such be chain specific, however, i believe we should review this anyway as i'm not sure this is any longer the most desirable onboarding procedure and plan to review this in relatively short order

```
Bee requires a Gnosis Chain RPC endpoint to function. By default this is expected to be found at ws://localhost:8546.

Please see https://docs.ethswarm.org/docs/installation/install for more details on how to configure your node.

After you finish configuration run 'sudo bee-get-addr' and fund your node with XDAI, and also XBZZ if so desired.

Created symlink /etc/systemd/system/multi-user.target.wants/bee.service → /lib/systemd/system/bee.service.
```

```
root@bee-1:~# sudo bee-get-addr

Please make sure there is XDAI and XBZZ available on the following Ethereum address on Gnosis Chain: 0x3bca067555b286c2d80ad4637977546dc42b56b7.

Learn how to fund your node by visiting our docs at at https://docs.ethswarm.org/docs/installation/fund-your-node

Once your node's wallet has received the funds it will begin joining the Swarm network.

See the docs for more information at https://docs.ethswarm.org/docs/.

root@bee-1:~#
```

**Comment by vandot** [comment]
Thanks @significance thing is that `bee-get-addr` is needed because it executed `bee init` and people get enough time to fund their node and later start it. If the node is started but is not funded it will fail and restart and it doesn't look nice :)
I am open for suggestions how we can improve this
