### ISSUE TITLE
Direct upload gets stuck forever

### ISSUE THREAD

**Issue by agazso** [ethersphere/bee#2946]
### Context
Uploading a file with the `swarm-deferred-upload` header set to `false` (also known as direct upload) may get stuck forever depending on the data to be uploaded. Uploading the same data with `swarm-deferred-upload` set to `true` (which is the default) succeeds and it seems to be cached after, because once it was successfully uploaded then the following uploads are going to be successful no matter how the header is set. 

### Steps to reproduce
There is an attached zip file which contains a file, which has 16384 bytes size and has `4d36fd00cd3d1eb376c2633a10a27287c90f48e696e401f8dec23548031a6f16` as content-hash.

Use the contained file and upload it to the `/bytes` endpoint with the `swarm-deferred-upload` header set to false:
```
curl --data-binary @4d36fd00cd3d1eb376c2633a10a27287c90f48e696e401f8dec23548031a6f16.bin -H "swarm-deferred-upload: false" -H "swarm-postage-batch-id: <use-your-postage-batch-id>" http://localhost:1633/bytes
```
[4d36fd00cd3d1eb376c2633a10a27287c90f48e696e401f8dec23548031a6f16.zip](https://github.com/ethersphere/bee/files/8662972/4d36fd00cd3d1eb376c2633a10a27287c90f48e696e401f8dec23548031a6f16.zip)

**Comment by istae** [comment]
The main culprit for this issue is the receipt depth check directly inside the pushsync protocol where after multiple failed attempts to send a chunk and attempted peers are skiplisted, the origin node selects itself as the storer node. If the PO of the relative to the origin node is below the node's depth, then an shallow receipt error is returned back to the pusher protocol.

**Comment by mrekucci** [comment]
The problem is as follows, we have a global skip list that applies to all chunks for a given peer (the peer is restricted for 5 minutes and deleted afterward). In [this PR](https://github.com/ethersphere/bee/pull/2348), a chunk-specific skip list was added, but peers in this skip list are never deleted (peers are just added there). If a push chunk ends with an error, the peer is added to this chunk-specific skip list and another peer is tried. If all peers we're connected to return an error (e.g.: due to the [stream reset problem](https://github.com/ethersphere/bee/pull/2843) we are currently experiencing), then the chunk-specific skip list contains all peers we can connect to. Due to this, the topology `ClosestPeer` method returns the `topology.ErrNotFound` error when we query for another peer. Since the `PUSH` section of the `pushStamperPutter.Put` method ignores all errors (except the `topology.ErrWantSelf` error), that causes the push chunk to be stuck in a perpetual loop.

There are several solutions to this problem:
1) fail-fast: if we encounter the `topology.ErrNotFound` error in the `PUSH` section, we do not try to resend the chunk, but terminate the process and return a network error to the sender
2) limited count of re-delivery: there is a possibility that we can connect to new peers in the meantime, so we can pause the process of sending the chunk when we encounter the `topology.ErrNotFound` error and try again after some time; we can try this several times and on a certain number of failures we can terminate the process as described by the fail-fast solution
3) flushing the skip list: in the `PushSync.pushToClosest` method, we can flush the chunk-specific skip list when we encounter the `topology.ErrNotFound` error and retry all the peers again after a certain amount of time; and also limit the number of retries (when reached, terminate the process as described in the fail-fast solution).
