### ISSUE TITLE
swarm.key decryption key is different when passing password via argv or config.yaml

### ISSUE THREAD

**Issue by Cafe137** [ethersphere/bee#2963]
## Context

1.6.0

## Summary

Download 1.6.0 Darwin ARM64 Bee release and make it executable

### Wrong

Create `config.yaml` with `password: Test`

Run `./bee init --config=config.yaml` and try to decrypt `swarm.key` afterwards

It fails with "Key derivation failed - possibly wrong passphrase"

### Correct

Do the same as before but omit `password` from `config.yaml`

Run `./bee init --config=config.yaml --password=Test`

The resulting `swarm.key` can be correctly decrypted with the same password

## Steps to reproduce

https://github.com/Cafe137/bee-password

**Comment by istae** [comment]
![image](https://user-images.githubusercontent.com/14264581/170866604-ddbfebc7-2ec5-486f-bc97-445386605c89.png)

So I ran this on a linux machine by adding this `const response = await fetch('https://github.com/ethersphere/bee/releases/download/v1.6.0/bee-linux-amd64')`
and the script worked fine with no errors. I wonder if the issue is present for for mac.

**Comment by Cafe137** [comment]
I tried it on Ubuntu 20.04 VPS and it is indeed correct

On my M1 MacBook the issue is reproducible with both `bee-darwin-amd64` and `bee-darwin-arm64`

**Comment by agazso** [comment]
I could not reproduce with `bee-darwin-amd64`
