### ISSUE TITLE
node unable to create or dilute batch

### ISSUE THREAD

**Issue by istae** [ethersphere/bee#3023]
⚠️ Support requests in an issue-format will be closed immediately. For support, go to Swarm's [Discord](https://discord.gg/XGNBEKktkD).

### Summary
For nodes 0 and 4 in our dev gateway cluster, create and dilute batch requests never complete.

### Observations
- The send transaction request to the xdai backend returns but the watch pending transaction never returns.
- The backed never makes the call or fails to make the call to the smart contract as observed by monitoring the postage contract events on the chain
- increasing the gas price by 10x does not change the behavior
- trying multiple endpoints did not fix the issue

**Comment by mrekucci** [comment]
The problem is this: in the `transactionMonitor.checkPending` method calls to the blockchain backend [`NonceAt`](https://github.com/ethersphere/bee/blob/master/pkg/transaction/monitor.go#L191) always return the same number on any block it receives (it's the number 28 on node `bee-0-0`). Different swap-endpoints were used (e.g.: getblock.io), but without success. The `go-ethereum` client, through which we make blockchain calls, was upgraded to the latest version, but that didn't help either. Overwriting the nonce returned by the call in the code to the latest one also didn't help because the [`TransactionReceipt`](https://github.com/ethersphere/bee/blob/master/pkg/transaction/monitor.go#L203) blockchain call has returned not found error.

**Comment by mrekucci** [comment]
On the node `bee-0-0` the nonce was reset by https://github.com/ethersphere/nonce-reset and the pending transactions were removed from the localstore.
