### ISSUE TITLE
Chainstate endpoint has missing `chainTip` property

### ISSUE THREAD

**Issue by agazso** [ethersphere/bee#3074]
### Context
Bee 1.6.2, macOS

### Summary
There is a [`/chainstate`](https://docs.ethswarm.org/debug-api/#tag/Status/paths/~1chainstate/get) endpoint that is supposed to report the postage syncing state during postage syncing. If I understand correctly the `chainTip` property should return where the syncing is at and I guess it is the `totalAmount` which it should reach. The problem is that the `chainTip` property is never returned, at least for me it was never returned during postage sycning, neither after it was synced.

## Task
Add the field to the actual API response and return it from the current blockheight of the chain backend that we are using.

**Comment by agazso** [comment]
Also the output of the same endpoint is not very intuitive. What does `block` and `totalAmount` mean if they change like this over time? 😄 

The `currentPrice` gives a slight hint.

![VirtualBox_Windows 10_05_07_2022_22_17_08](https://user-images.githubusercontent.com/230163/177409288-6c2bf3a3-db9b-437a-bc71-3811e2d13305.png)

**Comment by acud** [comment]
@agazso about the naming conventions of total amount and block number I suggest you consult with Viktor. The function of this API endpoint is for debugging purposes and therefore some of the lingo is internal and "not intuitive" as such. I would not burden this issue with the problem of naming conventions, especially as these conventions are already disseminated across the entire codebase and changing them in the API would require us to change the way we use them internally inside the codebase so that uniformity is achieved. If you find this such a big issue I would advise to open a separate issue about this. Thanks!

**Comment by swarmHaseeb** [comment]
@acud a PR for this token has been sent for review.

**Comment by swarmHaseeb** [comment]
@acud a PR for this token has been sent for review.
