### ISSUE TITLE
health: shows OK when its really not

### ISSUE THREAD

**Issue by darkobas2** [ethersphere/bee#3267]
⚠️ Support requests in an issue-format will be closed immediately. For support, go to Swarm's [Discord](https://discord.gg/XGNBEKktkD).

### Context
1.8.0-rc3

### Summary
bee is upgrading, doing the overlay address mint and health shows OK.

### Expected behavior
Bee is not really usable at this point so health status should reflect that

### Actual behavior
```
root@hhel3df1 ~ # curl -s http://127.0.0.1:1835/addresses |jq
{
  "overlay": null,
  "underlay": [],
  "ethereum": "0x78f02a1f7b1cc4c3f5c2e6973e21717faba9f397",
  "publicKey": "02db3f8219d2b19c27563541a99fd56c0d68471a2f692c74bb3e788139b8d12ce6",
  "pssPublicKey": "025583d660fc857facf20bd3348f313b11ce0dc5df2885ae92c70a88a09f0caa90"
}
root@hhel3df1 ~ # curl -s http://127.0.0.1:1835/health |jq
{
  "status": "ok",
  "version": "1.8.0-rc3-4e4262a3",
  "apiVersion": "3.0.2",
  "debugApiVersion": "3.0.2"
}
```

**Comment by vandot** [comment]
@darkobas2 health should be ok because Bee is ok, just doing mining.
If health would not be ok, pod would be killed by k8s in the middle of mining.
Readiness is also ok, but it shouldn't because Bee is not ready. But again that's only the issue for gateway. If you are using gateway-proxy in front of Bee readiness of gateway-proxy will be not ok and no gateway traffic will be served to that Bee.

**Comment by darkobas2** [comment]
Ok, thanx for explanation @vandot
