### ISSUE TITLE
`PUT /stewardship/{reference}` should allow setting a new postage batch

### ISSUE THREAD

**Issue by Cafe137** [ethersphere/bee#3541]
#### Summary

My understanding is that this "reupload" feature reuses the original postage stamp that was used to upload data. In other terms, this endpoint does not allow specifying a postage batch ID.

This feature request is to make this endpoint flexible so I can provide a (new) postage batch to handle cases when my postage batch has expired, but I have the content pinned and want to reupload that using the stewardship API.

#### Motivation

Keep data living when the original stamp expired.

Integrate this into the automatic content reupload feature of Gateway Proxy that ensures websites stay online on the Swarm network.

**Comment by ldeffenb** [comment]
I have accomplished this completely outside of the bee node using the /chunks debug API.  On second thought, it does require a modified bee node in order to actually query the stamps that are protecting a chunk.  I did this with a new method on the /stewardship API that I call "track" that returns all chunks involved in a reference, including all BMT chunks, but NOT traversing related mantaray manifest nodes, along with their active stamp (according to the responding node) and the internal pin-counter (for diagnostic purposes).

Once chunks have been identifies as needing to be "re-stamped", I get the /chunks content, then DELETE the /chunks, and finally re-upload the /chunks with the new stamp batch and the swarm-pin tag.   Obviously this is risky as there is a very short window where your local pinning node will no longer have the chunk until the re-upload succeeds.

You can see this in the reStamp routine in Swarming-Wikipedia repository:
https://github.com/ldeffenb/Swarming-Wikipedia/blob/main/src/restamp-reference.ts

Note that all of these various mantaray manifest processing scripts assume a modified bee node where the stewardship and pinning APIs do NOT traverse mantaray manifest nodes.  And reStamp in particular requires the added -X TRACK method on the stewardship API to reveal the stamps on individual chunks.

**Comment by istae** [comment]
this feature is now implemented.
