### ISSUE TITLE
only reachable peers should participate in the storage incentives

### ISSUE THREAD

**Issue by istae** [ethersphere/bee#3560]
Bee nodes only sync with reachable peers so it's only natural that external connectivity is a requirement for participation for storage incentives.

**Comment by ldeffenb** [comment]
What is your definition of "reachable"?  Do you mean ""reachability": "Public"" as shown in /topology or something else?  I believe that "Public" reachability means that the node is accepting inbound connections, which is not a sycning requirement.

Just because a node isn't accepting incoming connections, doesn't mean it isn't well-connected on the outbound side and therefore still likely to be syncing since both push and pull sync protocols don't care which direction the connection was established, but they work over both inbound and outbound established connections.

**Comment by mfw78** [comment]
While it may be true that a node may be well connected on the _outbound_, there really should be some incentive towards those that are reachable _inbound_. One particular cause for concern may be an increase in CGNAT deployments, where more nodes running behind CGNAT induce a requirement for nodes that can accept _incoming_ connections.

Without fragmenting things too much on the incentive side, it does seem that those that accept inbound connections should benefit more, though this could be on the side of bandwidth sharing (acting as a relay as such) and therefore perhaps more tuning of the swap bandwidth protocol to take into account this incentive structure?

**Comment by istae** [comment]
atm, nodes that are not capable of inbound connections are skipped for pushing and retrieving chunks. These node only store chunks that come in through pullsyncing, and as such, these nodes maintaining an active reserve adds no value to the network.
