### ISSUE TITLE
Bee API returns inconsistent names for Swarm hash(?)

### ISSUE THREAD

**Issue by crtahlin** [ethersphere/bee#3604]
### Location
![image](https://user-images.githubusercontent.com/1554520/204562858-314fa653-e3e6-49d9-b6ec-0ef99514486a.png)

### Description
Two different terms are used for the Swarm reference hash in return from API, as shown in screenshot : "etag" and "reference". I would expect just one term (unless they are a different thing somehow?).

**Comment by agazso** [comment]
The [HTTP `ETag` header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag) is an identifier for a specific version of a resource. It lets caches be more efficient and save bandwidth, as a web server does not need to resend a full response if the content was not changed. 

This is utilized due to the fact that the resources uploaded to the `/bzz` endpoint are immutable, so the returned reference can be also used to identify the cached version of a resource. So this is not a bug, but rather a feature and it is actually documented if you check out the `201` response part of the documentation of the [POST method of the `/bzz` endpoint](https://docs.ethswarm.org/api/#tag/BZZ/paths/~1bzz/post).
