### ISSUE TITLE
File downloaded from Swarm is corrupt

### ISSUE THREAD

**Issue by crtahlin** [ethersphere/bee#3714]
⚠️ Support requests in an issue-format will be closed immediately. For support, go to Swarm's [Discord](https://discord.gg/XGNBEKktkD).

### Context

![image](https://user-images.githubusercontent.com/1554520/213648376-35e7766a-8364-4e94-be1c-998c0da2fc3f.png)

![image](https://user-images.githubusercontent.com/1554520/213648444-8c1c8566-a50b-4f2b-afd0-2995ec213fe9.png)

### Summary

Using [swarmsync](https://github.com/datafund/util_swarmsync) tool to upload files to Swarm. swarmsync uses Bee to upload (does not do its own chunking or anything similar). The upload is supposedly deffered=FALSE.

Swarmsync writes (supposedly) successful uploads to a JSON file. Relevant is this snippet:

```
{"file": "/media/crtah/GREATDATA/download.kiwix.org/zim/wikipedia/wikipedia_ar_football_maxi_2022-11.zim", "reference": "87eefb6b6d462914d62ccd01fb9fa6568d542a2cc464e84ef084c5a283167943", "size": 852422156}
```

It refers to a file chosen at random from the list of uploaded files. The original size of the file is 800+ MB. 

Trying to download the file using its reference (using Swarm desktop, swarm-cli, Swarm gateway), the file is just around 360MB. And a bit different size each time, depending on which way it was downloaded. 

### Expected behavior

Applications used to download the file should not return the file if it is not complete, identical to the original file. 

As per current research, the Bee client does not recognise (?) an error when downloading files. It should handle such a situation in a way, that applications (browser, swarm-cli,...) recognize that the file is currupt. 

### Actual behavior

Screenshot shows different downloaded sizes for same file:

![image](https://user-images.githubusercontent.com/1554520/213653954-379da31d-5cf4-4ab7-982c-05b3b16f0b6a.png)

### Steps to reproduce

Not sure how to reproduce, but probably uploading a larger file and trying to download it. 

The specific file reference hash is: `87eefb6b6d462914d62ccd01fb9fa6568d542a2cc464e84ef084c5a283167943`

### Possible solution

Error handling of downloads by Bee.

**Comment by crtahlin** [comment]
I have re-downloaded some 550 files that were uploaded and some 150 of them were different then the uploaded ones. 
About 100 files fail stewardship check. Not sure if same ones.

**Comment by crtahlin** [comment]
Downloaded files were truncated and smaller than the original files.

**Comment by ldeffenb** [comment]
Truncated files are caused the by the retrieval API (/bytes and/or /bzz) not returning an error if a required chunk is not found.   Instead, it just returns a success and a short and therefore corrupt file.   So this "different contents" is actually the same thing as a non-playable video for instance.  Depending on what is in the missing chunk, some files can handle seeking beyond the problem with a byte-range GET, but some will not do that because of the way the actual data is indexed by the chunking algorithm (I can't remember the name of it at the moment).

**Comment by aloknerurkar** [comment]
@crtahlin 

Sorry for getting back late. As @ldeffenb mentioned, these files are not corrupt, they are incomplete retrievals. This is because we have some optimizations on the API to allow HTTP response to return early as we retrieve the content in the background. We use a look-ahead buffer which will retrieve parts of the file and return it as it arrives from the network. We send the response as soon as we have read some small initial parts of the data.

The problem here is that without sending a Response code, the client cannot start reading the file. This is why we return 200. We do send the `Content-Length` header and there are some browsers that can identify this mismatch when they read and report errors. But maybe not all browsers/curl can figure this out. If we remove this functionality, we would have to buffer the file till we send it back and this would make things too slow to use.

Why the retrieval's are failing is a different problem. This is more like an ongoing process for us as we try to identify issues in the protocols/storage layer of bee. There is a full rewrite of the storage layer in progress that will improve the situation. But there is no immediate thing we know of.

Possible solutions/workarounds:

1. The API supports range queries. So you could potentially do this in the application layer where you can query separate ranges and these would be separate retrieval requests.
2. Implement some kind of retry logic that would identify length mismatch and retry with some delay. It could be some transient issue with the network that the retrievals fail. Maybe new links would be available.

The other thing we can do is implement the new HTTP status code [103 Early Hints](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/103). This is a new code and not all browsers support it yet. The purpose of this code is similar to where we send the initial 103 code and start sending data. If the entire retrieval happens, we send 200. The only problem here is the compatibility of browsers. This could break it for people using unsupported browsers.

**Comment by nugaon** [comment]
For me, the `Decompressed-Content-Length` appears in the header instead of `Content-Length`.
![Screenshot from 2023-02-13 13-10-07](https://user-images.githubusercontent.com/50576770/218685518-0956eddf-a297-4473-858f-f091028acfb7.png)

**Comment by significance** [comment]
can we hash the response and check it matches the address, and if not return 500?

it would maybe make more sense than returning half retrieved files 😀

**Comment by ldeffenb** [comment]
In my experience, truncated files result from non-retrievable chunks in the BMT.   Whether or not compression occurs really won't affect the retrievability of the complete file, but compression may make diagnosis of the root cause more difficult.

**Comment by aloknerurkar** [comment]
In the latest version of Bee, we return the correct `Content-Length` header. This enables us to detect failure at the client level and these downloads will no longer be returning successes.
