### ISSUE TITLE
remove redundant entries in upload/download

### ISSUE THREAD

**Issue by mortelli** [ethersphere/bee#463]
because the file upload and download functionalities were implemented before manifests, the current code uses variables from `collection/entry` to reference metadata about a file (before referencing its actual content).

now that we have json manifests, we have a redundant entry in the resulting references:

> dir manifest → `manifest` entry →  `collection` entry → file content

consequently, `entry.Entry` variables should be removed from the code and just `manifest` entries should be use in their stead.

this issue is a technical debt follow-up issue stemming from #452 and #447.

**Comment by mortelli** [comment]
we've discussed this further with with @zbiljic and we're not entirely sure about how to proceed with this issue.

we'll try to set up a call with @zelig to sync about this.

**Comment by Eknir** [comment]
@zbiljic , could you tell me what is the status here? Is this something we want to resolve before the next release?

**Comment by zbiljic** [comment]
@Eknir This is related to the old discussion we had (little over a month ago), that I explained more detailed here: https://github.com/ethersphere/bee/pull/591#discussion_r473879567.

My initial implementation was one way ('bytes'), after which we decided on another ('file'), and this issue was for asking the question whether it should be returned to previous way ('bytes'), for storing content of manifest-related files.

Current way is storing files as through the 'files' API, which is by itself fine.

More detailed discussion is needed on whether we want to leave it like this, or change it to storing file bytes (as is using 'bytes' API).

**Comment by Eknir** [comment]
@zbiljic : to me you are the technical owner of this part. I recall a discussion with @mortelli, but not with @zelig about that. At that time, nobody was really sure what to do. You had some arguments for `bytes`, and @mortelli had some arguments for using `files`. If, in hindsight, the decision is wrong, please feel free to add it back.

**Comment by zbiljic** [comment]
@Eknir There was not wrong decision. Each of us had arguments for one or the other side. I had no special idea whether one or other is better. In the end on the meeting with Viktor we decided to go with `files` API.
We can discuss about changes.
