### ISSUE TITLE
Connecting to bootnode fails

### ISSUE THREAD

**Issue by martinconic** [ethersphere/bee#4907]
⚠️ Support requests in an issue-format will be closed immediately. For support, go to Swarm's [Discord](https://discord.gg/XGNBEKktkD).

### Summary
Connecting to bootnode fails:
```
"time"="2024-11-20 15:49:53.360738" "level"="warning" "logger"="node/kademlia" "msg"="connect to bootnode failed" "bootnode_address"="/ip4/49.12.172.37/tcp/32490/p2p/QmZsYCbkUXWpfR34PmUwMJvHwJtGfbcMMoAp1G2EydkpRA"
"time"="2024-11-20 15:49:53.360749" "level"="debug" "logger"="node/kademlia" "msg"="discover to bootnode failed" "bootnode_address"="/dnsaddr/sepolia.testnet.ethswarm.org" "error"="discover /dnsaddr/bee-0.sepolia.testnet.ethswarm.org: discover /ip4/49.12.172.37/tcp/32490/p2p/QmZsYCbkUXWpfR34PmUwMJvHwJtGfbcMMoAp1G2EydkpRA: network status unknown: connect full close stream reset"
```

**Comment by istae** [comment]
with https://github.com/ethersphere/bee/pull/4871 bootnodes started blocklisting peers
which caused first time connecting peers to be blocklisted almost instantly because of protocol requests like pullsync.
generally these requests are not fired after the warmup period but if the warmup period is reduced then the fresh node can be blocked from joining the network through the bootnode.

the fix should be that peers should be sending any protocol requests to the bootnode, ever which is handled in  https://github.com/ethersphere/bee/pull/4909
