### ISSUE TITLE
Panic on tar upload

### ISSUE THREAD

**Issue by Eknir** [ethersphere/bee#526]
When a certain tar is uploaded to bee, the bee node panics.

This issue was discovered by @ralph-pichler on the [testing session](https://hackmd.io/hVr1MklhSRGcbuM7DgTypQ?view).

Please provide more details if you have them @ralph-pichler 

![image.png](https://images.zenhubusercontent.com/5e7c6d2ce969e644bdebbf30/894e3118-536c-4e22-af37-4af914740f87)

**Comment by Eknir** [comment]
@mortelli

**Comment by zbiljic** [comment]
This issue exposed problem with `ChunkPipe` implementation.

The thing that happened was that the JSON manifest that was created was larger than double the size of the `swarm.ChunkSize` (which is maximum buffer size in `ChunkPipe`). Since the manifest was marshaled into bytes in memory, and from those bytes the new `io.Reader` was created using `bytes.NewReader(...)`, all bytes were being passed at once int o the `Write` function in `ChunkPipe`.

This came during a call to `io.CopyBuffer` in our `file.SplitWriteAll()` function. Since all the bytes are already in memory, the `bytes.Reader` implementation was sending all of them into the `Write` function during copy.

This probably never came up as until now all calls were through HTTP request, and were chunked, and not large enough to trigger issue that caused this panic to occur.
