### ISSUE TITLE
Plain text response

### ISSUE THREAD

**Issue by Eknir** [ethersphere/bee#528]
Downloading a directory with curl: 

`curl "localhost:8080/bzz/2058bf6d8e9d693ec7820fc04a1c700992fb63b9dcd819fbaf0d97ce59a1fb46/Wheel of Time (2003).avi BG subs - Колелото на времето-UJZAb830qEc.mp4" -i`

Returns a plain-text error (not JSON encoded). 
```
HTTP/1.1 400 Bad Request
Content-Type: text/plain; charset=utf-8
Connection: close

400 Bad Request
```

@acud :
```
I think in this case json response should be return if json accept header is set

Since browsers might display some custom error page for a generic empty error

I’m not sure tho. Need to check
```

**Comment by Eknir** [comment]
@mortelli

**Comment by Eknir** [comment]
@janos : url path needs to be unescaped (html.Unescape) before getting the manifest path

**Comment by zbiljic** [comment]
This error is from Go [net/http/server.go](https://golang.org/src/net/http/server.go) on invalid request; in this case not properly encoded URL, which `cURL` does not do for user automatically. The browsers and some other tools are more forgiving.

The response is from default case for invalid request (found here [`publicErr := "400 Bad Request"`](https://golang.org/src/net/http/server.go#L1886)). The error that happens is `malformed HTTP version "with space HTTP/1.1"`.

Note that the same things happens even with simples HTTP server:

```go
package main

import (
	"fmt"
	"net/http"
)

func main() {
	http.HandleFunc("/", HelloServer)
	http.ListenAndServe(":8080", nil)
}

func HelloServer(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "%s\n", r.URL.Path[1:])
}
```

What actually happens is when we have some URL with spaces (using `cURL`, not encoded), such as `curl "http://127.0.0.1:8081/bzz/ test"` is that request that is send is following:

```bash
> GET /bzz/ test HTTP/1.1
> Host: 127.0.0.1:8081
> User-Agent: curl/7.54.0
> Accept: */*
```

And due to the way the request is processed (method first, URL second, and then HTTP version, up until terminating character - newline), anything after the URL is considered HTTP version, which in this case is `test HTTP/1.1`. Since this is not valid for HTTP version ([source](https://golang.org/src/net/http/request.go#L771)), because prefix `test ` is there, error is returned.

Not sure if I am missing something, however unless we plan to use some custom HTTP processing library, we will not be able to return JSON response for this (and few other) specific requests.
