### ISSUE TITLE
Instant chunk repair

### ISSUE THREAD

**Issue by jmozah** [ethersphere/bee#548]
# User story
Chunk repair happens in an asyncronous way today. The client tries to download a chunk, if the chunk is not found, it triggers the chunk repair and returns http 202. The client needs to come after sometime and try getting the chunk again.
This is not good from the UX perspective. So when a chunk is requested using PSS message, the idea is to send the response with the requested chunk back so that the chunk can be given to the client.

## Acceptance criteria
When a chunk is not there in the network, and it is requested, chunk repair should be initiated and chunk given back in the same request itself.

**Comment by Eknir** [comment]
We should use PSS stamped enveloppes for this @zelig

**Comment by jmozah** [comment]
https://github.com/ethersphere/bee/pull/676

**Comment by Eknir** [comment]
It was decided to not attempt to merge #676. The reason is that instant chunk repair is not a priority right now and merging it would risk destabilizing the feature and/or other components. Nevertheless, we keep the issue open and the PR will be connected to it, so that it will serve as a reference point when we attempt to implement in for the second time.
