### ISSUE TITLE
Improve UX of Global Pinning

### ISSUE THREAD

**Issue by acud** [ethersphere/bee#646]
Query param option is clunky to use, improve either by ENS fields to reference or by other means.

**Comment by Eknir** [comment]
There was a conscious choice not to use ENS or manifest to communicate the target for global pinning. The reason is that the target can be communicated via many different ways, each way having it's own merits and disadvantages. Examples include:

- Communicate target via paper to your friend
- Communicate target as owner of ENS record
- Communicate targets via feed
- Communicate target via manifest

Communicating the target via the query param allows each of these options, and gives the freedom to experiment. Therefore, it is in line with the non-opiniated bee. I am tagging @agazso , as this is something that should be, IMO, solved by second layer. @agazso , could you make sure that this is noted in the JS-backlog?

@acud, could you close the issue if you are satisfied with the answer and, if not satisfied ensure that we resolve this question asap (and then close)?

**Comment by Eknir** [comment]
Closing the issue. @acud , please re-open if you don't agree with my decision.
