### ISSUE TITLE
Manifests outstanding tasks

### ISSUE THREAD

**Issue by acud** [ethersphere/bee#648]
Outstanding tasks after implementing #418

- upload empty directory - https://github.com/ethersphere/bee/issues/481
- Support outstanding manifest API endpoints #661 
- Support directory listing on `bzz` endpoint #662

-- closed but still relevant --
- Access website on root path (/) #658 
- manifest default path #647

**Comment by Eknir** [comment]
removed #482, #462 and #463 from this list, as they were already closed. @acud

**Comment by Eknir** [comment]
@zbiljic , this issue still links to #658 and #647 because of [this comment](https://github.com/ethersphere/bee/issues/658#issuecomment-692712282). Is there some improvement which is on the top of your head still?
If it is not too much effort, could you make an issue out of that, for further reference?
After the issue is made you can link that issue under this epic (both link in the text and assign the issue to the epic) and then remove the stale links (#647 and #658)

**Comment by zbiljic** [comment]
@Eknir The comment you referenced is obsolete. There were some changes that were done, that cover changes that Janoš did, as well as cover some additional cases. No further changes were planned in relation to that.

**Comment by agazso** [comment]
This issue is a catch-all issue and as such it is not very actionable anymore. The two currently outstanding issues are:
- https://github.com/ethersphere/bee/issues/662
- https://github.com/ethersphere/bee/issues/2891

Those issues were updated with recent/relevant information, so those can be tracked from now on and this one can be closed.
