### ISSUE TITLE
Support directory listing on `bzz` endpoint

### ISSUE THREAD

**Issue by zbiljic** [ethersphere/bee#662]
# Task

When accessing directory on `bzz` endpoint, listing of existing files and directories should be listed, instead of returning error message (since no file on that path exists).

## Acceptance criterea

When user is accessing root or some other directory path on existing manifest hash, some kind of directory listing should be returned (comparable to how it works in browsers for some websites).
Suggestion has been made that some JSON object structure could be returned.

**Comment by Eknir** [comment]
Putting this on hold, until a user requests it. Perhaps @jmozah , do you need this?

**Comment by agazso** [comment]
This would be indeed nice to have.

A possible workaround for this is to access the manifest with a client side library, such as the [manifest-js](https://github.com/ethersphere/manifest-js).

**Comment by agazso** [comment]
To follow up on this topic: there were discussions in the swarm team and the outcome is that the direction with manifests are going to become a generic key-value store, rather than mapping it to a filesystem oriented abstraction.

One of the biggest argument for this decision was that filesystems are tied to operating systems, therefore they are less universal and has their own idiosyncrasies on each platform. A generic key-value store can be used to represent a filesystem by convention and that can be done in the application layer instead of doing it in Bee.

Therefore I am closing this issue.

**Comment by ldeffenb** [comment]
> To follow up on this topic: there were discussions in the swarm team and the outcome is that the direction with manifests are going to become a generic key-value store, rather than mapping it to a filesystem oriented abstraction.

Wait, to help me understand this.  If manifests and the /bzz/reference/path/to/file capability are removed from the bee node, just how does the swarm expect to conveniently store web site file structures without extensive modifications to every image and anchor relative links?

**Comment by agazso** [comment]
First of all, no existing capability is planned to remove from Bee, at least not anytime soon and even if that happens there will be an alternative way or tooling to provide the existing functionality.

However this decision means that currently there are no plans to extend the current API to support working with manifests as directories and that includes features such as this one (e.g. listing directories).

**Comment by agazso** [comment]
Maybe what is not clear, that the current manifest implementation is already a generic key-value store, and the `/bzz` endpoint treats the key as a path. While this works to some degree and it enables things such as serving directories and files over it, this abstraction breaks at some point, e.g. when using a key which is not a valid path. 

What is not a valid path depends on the operating system, but also listing the keys raises questions, because in JSON you cannot represent all possible values, so these are all scenarios where the abstraction breaks and therefore on the long term it would take a lot of effort to maintain and document all the edge-cases.

**Comment by ldeffenb** [comment]
Thank you for quelling my fears about losing capabilities that currently work with every bee node out there!  Long live the mantaray manifest with transparent /bzz/reference/path/to/file access!
