### ISSUE TITLE
Add feature for installing Bee cluster via Beekeeper

### ISSUE THREAD

**Issue by svetomir** [ethersphere/bee#814]
Add feature for installing Bee cluster via Beekeeper

**Comment by Eknir** [comment]
@svetomir , I put this in `active sprint` pipeline (`Backlog` workspace). You can track the status of this issue in the `Active sprint` workspace. Would be best if you could propagate this issue to an epic, and make issues for the steps which you still need to achieve in order to complete that epic. Then, you can assign the PRs to the individual issues.

**Comment by svetomir** [comment]
This is done. Branch k8s.
