### ISSUE TITLE
pullsync: sync only in nn

### ISSUE THREAD

**Issue by acud** [ethersphere/bee#818]
Pull sync should sync only within neighborhood
This should be a single changeset and needs thorough testing that the cluster still functions correctly in configuration change (i.e. depth changes)

carry over from #329 

Acceptance criteria:
- should be reflected in the integration test

**Comment by Eknir** [comment]
The reasoning for this is that if pull sync would sync outside of nearest neighborhood, pull sync could be used to upload files, which would break the spam protections measures which we have in place for push sync.

**Comment by Eknir** [comment]
@acud, what is the status of this issue?

**Comment by Eknir** [comment]
We should be aware of the side effects to this of the network. @acud , please specify further.

**Comment by Eknir** [comment]
@zelig , after a discussion with Elad, I want to bring up why we need this one at all. The main problem is that in Swarm, neighborhoods are not symmetric. Hence, syncing only in nn can cause problems of content not being synced. I personally had the feeling that the main reason for this issue was to dis encourage using pull sync for upload. However, since pull sync already does not sync bin-0, it is already not likely to be used for upload. If we see a lot of traffic from pull sync which tells us that people are using it for upload, we can come up with a solution that time. Anyways, the "damage" is not big.

Could you let me know if there were other issues and how you feel about closing this particular issue (for now)?

Best,

**Comment by zelig** [comment]
sorry  but the current  behaviour is legacy  from times when there was no pushsync.
It simply is wrong to pullsync non-neighbourhood bins.
Asymmetric neighbourhoods have no added benefit from allowing syncing non-neighbourhood bins.

**Comment by Eknir** [comment]
@zelig , thanks for your attention on this. As far as I understood, the main reason why we don't want to sync non nn bins is to prevent people to upload their content via pull sync. However, since we are anyways not syncing the zero-bin (@acud told me this), you cannot upload 1/2 of your content anyways. Apart from this, only syncing in nn can cause some content not to be synced that should have been synced, due to asymmetric neighborhoods.
I can prioritize this issue, but I would like to have a positive statement as to why we need this (not: it is legacy) and I also want to be assured that it is not messing up with what we have (ideally both theoretically as well as empirical validation in tests).
