### ISSUE TITLE
Unpin set of chunks

### ISSUE THREAD

**Issue by Eknir** [ethersphere/bee#824]
# User story

## Story
As a local file pinner, I want to easily unpin a set of chunks--belonging together

## Acceptance criteria

- User can unpin a file/manifest/bytes with one command
- Bonus points (not required): user can unpin a set of files (not referenced by one roothash) with one command. E.g. unpin all files, which were authored by person xyz => we can tag files when we pin them and use this tag to manage the pins afterwards.

## Background

Currently, we expose unpin{chunk}, but this is not very user friendly. Surely, a user can create script to call unpin{chunk}, such that all chunks under one file are unpinned. We want to allow this freedom (don't remove unpin{chunk}), but add a more convenient endpoint to the user as will.

Talking with @janos, we were considering the implications of unpin{chunk}; does this set the pincounter to 0? Does it decrement the pincounter? Do we perhaps need two APIs, one to set the pincounter to 0 and one to decrement it? 

## Tasks

| Task | Assignee |  Done (1), or 0 |
| ------ |------------| -----|

**Comment by ldeffenb** [comment]
I like the "tag files when we pin them" as the user can do arbitrary groupings.  That would be very handy for my current usage.

Personally I don't see a need for the "set pincount to zero" as that could be done easily with the current API.  I'm already querying the pin for the count and looping the unpin API for that count.  It works fine that way.

My concern with a "slam to zero" would be if a given chunk/file was involved in mulitiple pin-sets.  Just because one set wants it completely unpinned, if it is in another set, it should still remain pinned IMHO.  I know that gets really ugly really quickly, but I think it is important to not inadvertently completely unpin a chunk/file as that could cause content to be permanently lost even to recovery if the pins were on a global-pinning node.

**Comment by jmozah** [comment]
This is something that we need in FairOS. For now i cannot unpin a file or a collection and its a pain.

**Comment by Eknir** [comment]
We will plan a meeting to discuss this and it's interference with /unpin/{chunk}

**Comment by Eknir** [comment]
It was decided today that the following operations are useful:

- decrement/increment pin counter for all chunks under a specified root chunk
- decrement/increment pin counter for an individual chunk
- set pin counter to 0 for specific chunk

For all the pin operation on individual chunks, we must warn the user that it might lead to inconsistencies. However, we want to allow these endpoints in order for users to manage their collections outside of Bee and to let Bee to be independent from notions such as files or manifests.

Tagging certain chunks, belonging together is nice, but we decided against this, to keep the purity of the Bee client. Tooling can be developed that keeps track of which (root) chunks belong together.

**Comment by zbiljic** [comment]
manifest-related PR: [ethersphere/manifest#13](https://github.com/ethersphere/manifest/pull/13)

**Comment by zbiljic** [comment]
@Eknir Note that all issues for this Epic are done (not sure where to move it now).

**Comment by Eknir** [comment]
You may close it. Thanks @nemanjaz!
