### ISSUE TITLE
bin 0 pinning ineffectual 

### ISSUE THREAD

**Issue by acud** [ethersphere/bee#828]
when a user pins a certain arbitrary amount of chunks locally, half of them would fall under bin 0, and the rest under higher bins.

the chunks would first enter into push and pull sync indexes. at first, all chunks would be pushed with push sync. all chunks would be in the pull sync index, and local pinning provides the assurances that they do not get garbage collected. the pull sync index would provide assurance that the chunks get synced when network configuration change happens.

the problems:
- if chunks that fall under bin 0 get garbage collected, they will never be re-synced, even though they are in the pull index and in the retrieval index, this is due to pull sync not syncing bin 0 chunks
- there is no way to trigger re-syncing of these chunks right now
- effectively they will be synced out of the pinning node only once (on upload, using push sync)
- a pinned chunk that have been synced to a peer that has already received the chunk via pull sync will not be accepted twice, since its interval is already sealed

possible solution:
- build tooling to traverse a root hash and push all related chunks to the network. needs extra tooling on the manifest side

**Comment by Eknir** [comment]
@acud, thanks for writing this down and sorry for not answering (yet). 

As we spoke about:

Pull sync should indeed not sync outside of the neighborhood, as it allows for uploading data into Swarm outside of the push sync protocol. The push sync protocol has (will have) certain protections in place, such that not all content can be pushed to Swarm. If we would allow pull sync to send arbitrary information to the network, then these protections are in vain.

Now, to still be able to upload (missing) content to the Swarm as a local pinner, a local pinner must be able to say <push chunk a to the network> or <push all chunks under this root hash to the network> or <push all chunks that belong to this tag to the network> (currently tags are not provided for locally pinned chunks, but #824 hints at it).

This operation is effectively also what global pinning does, and I think it should be opened up to align with our strategy to open both the lower and the higher-level APIs. 

With the possibility to push locally pinned files, global pinning becomes possible without using the global pinning feature of Swarm. You could, for example, get a message that content is lost via email (instead of PSS) and then manually trigger push sync for that content. Also, it will make global pinning in JS easier to implement.

Obviously, there will be some technical barriers to implement this (as you mentioned tooling to traverse root hashes (of manifests)). But I think it will be worth the effort. 

Tagging @janos (as he was in the call where we spoke about this) and @zelig

**Comment by Eknir** [comment]
In the meeting today, we settled that not pull syncing locally pinned chunks is intended and that the feature behavior is as intended. An issue (#852) was created to ensure that content which is locally pinned once can be easily re-uploaded via push sync.
