### ISSUE TITLE
Progress on upload

### ISSUE THREAD

**Issue by Eknir** [ethersphere/bee#918]
# User story

## Story

As a user of Swarm, I want to know the progress of my upload without having knowledge of bee internals, such that I know when the upload is finished and I can estimate how long it will take until it is finished.

## Acceptance criteria

- Based on the information in tags, we can create a progress bar that shows percentage until completion
- This information, does not rely on bee-internals (as the current tag implementation does)
- An upload that is complete shows 100% completion

## Background

- In [https://github.com/ethersphere/bee/issues/893](893), @janos explained that tags can show as if no progress is made anymore, but in fact this is expected behavior if the content is already pushed before.
- A dapp developer wants to rely on this information to trigger other actions

## Tasks

| Task | Assignee |  Done (1), or 0 |
| ------ |------------| -----|

**Comment by Eknir** [comment]
@zelig an d@eknir sync on this together, to look at the design of the API and implementation. Basically, figure out if design is good enough.

**Comment by Eknir** [comment]
Related: #1007

**Comment by Eknir** [comment]
There has been a meeting with @zelig and @janos , where we spoke about the following:

Architecturally, tags are not implemented in the most optimal form. It would be most perfect to make a service out of tags and inject that service into the components that use tags, instead of passing around state. 
@janos, could you please write down succinctly (in a comment under this issue), the architecture you have in mind, together with a crude estimation (in developer days) to complete this architecture?

@zelig mentioned that something that should happen anyways is to only increment tags upon the first attempt sending attempt. Here, I would like to put my question mark, as in the past, it has proven useful for spotting problems to know that the node is continuously attempting to send.
Continuing on this thought, what should be ultimately useful for the user is the `tag.Synced` counter, as this counter gives the user the guarantee that the content is synced (and hence available).

**Comment by janos** [comment]
The idea about Tags service is to avoid passing the Tag instance, which includes storage.StateStorer among other fields. This would bring more clarity where tags are used and how the state is managed.

The Service would allow implementation which is responsible to store and manage tags and their counters just by their references (IDs or associated address). The Service would be injected into other components that need to query or update tags. Also the Service could contain the iterator method on the tag that would send counter changes in a channel or a callback function in order to be streamed to the caller, similarly to what localstore subscriptions work. This can be used for a websocket tag endpoint, for example, as a convenient endpoint for a user to track the progress.

The service would be responsible for persistence, or no-persistence, purging of old tags, among basic functionality to manage their state.

This is just a description of idea, I did not write the exact interface with expected methods. This would be defined if this approach is accepted and delegated. Even this was informally discussed last year in several occasions, mostly when larger changes to tags were made.

**Comment by Eknir** [comment]
We spoke about this feature today in the backlog refinement and agreed that we should distinguish the user focused feature with "get status of upload" with the more debug related things for tags (e.g. sent is continuously incrementing). 

I would propose to continue with @zelig s comment to ensure that `state.sent` only increments once and then expose via some other endpoint the information of how often our node is attempting to sent.

**Comment by Eknir** [comment]
I have an additional question on the `Seen` status. To me, this also smells like bee-internals and should probably not be exposed to our users. However, if I'm correct, the Bee node currently won't reupload content it has already seen, so without the `Seen` status, a user might be clueless as to why the upload is not completing. A related issue is #1051, as this issue will change the behavior of the node to reupload content, even if it is already seen.
