### ISSUE TITLE
Enable bee to start as a Windows Service

### ISSUE THREAD

**Issue by vandot** [ethersphere/bee#935]
# Task
Currently bee cannot start as a Windows service, it fails with
`Error 1053: The service did not respond to the start or control request in a timely fashion`
It looks like that solution is to change how bee is being started, either this [svc](https://github.com/golang/sys/blob/master/windows/svc/example/service.go) or this [kardianos/service](https://github.com/kardianos/service)
## Acceptance criterea
Bee can be started as a Windows Service

**Comment by Eknir** [comment]
Hi @metacertain , could you please attach your PR to this issue?

**Comment by Eknir** [comment]
@metacertain @vandot , I move this to the decommissioned pipeline. @metacertain , please attach your PR to this issue, so we can pick up the work easily when we work on it after the sprint.
Thanks

**Comment by zbiljic** [comment]
I have checked state of Windows service with @vandot, and have some pending changes.

Main problem with the current changes/branches that relate to this is that when Bee is started as a service is that we lose logging output. Even though logs are configured to STDOUT, they are not going anywhere. Two main options that can be considered are to either support logging to some file (which is quite a work in itself), or use Windows event log for logs for service (`build-msi-2-eventlogger` branch). Event log seems to be the place for logs from services.

Other problem is with actual way of starting Windows service.
There is a bit specific way on how the service should be started, and simple example can be found here: [golang/sys/blob/master/windows/svc/example/service.go](https://github.com/golang/sys/blob/master/windows/svc/example/service.go).

Issue I have found here is that name of the service must be global thing, i.e. user cannot create his own Windows service, and Bee can be started as Windows service (of course, unless we expose some additional config). This is not much of a problem, just a thing to note. Creating and starting service must be done with same service name, or the process will not start.
It is quite possible to have Windows-specific code, which will not interfere with other versions.

The [kardianos/service](https://github.com/kardianos/service) library can be used here, mostly to simplify the amount of needed code for starting service. Because it does support many other systems, which we already have support for, we can only use it just for starting the service (removes much of boilerplate).

What I suggest here is to include new CLI command, which would be Windows-only, and would have commands for installing and removing Windows service, that can be called by system that provides Bee package (or manually by user). This would be something like:

```bash
# Install Windows service
bee service [install|create]

# Remove Windows service
bee service [uninstall|remove|delete]
```

**Comment by Eknir** [comment]
Hi @zbiljic , thanks for the effort you put in writing this down.

So, what you suggest is to use https://github.com/kardianos/service as windows-specific code in our Bee codebase and then use windows event log to log our console output?

If the windows event log are the standard to use, this seems acceptable to me. Regarding the service, we should document this properly, but I don't see this as a blocker.

The only doubt that I am having is with regards to maintainability and effort to implement this. Could you please let me know the required effort (approximately) to implement logging and windows service creation, as well as maintenance requirements if we officially support windows.

**Comment by zbiljic** [comment]
Yes @Eknir, that is my suggestion. The use of this library can be considered as side thing, just to make things easier.

As far as the work goes, on the one hand we would have the changes required in the code, to add support for another CLI command (used just for Windows), and these other two sub-commands. The code required for sending logs and setting up actual service startup is already done (on separate branch). The other part is actually setting up required installers, which @vandot is familiar with.

This sub-command changes should be pretty trivial, I think most of the "work" be to actually decide on the name of the commands and their descriptions. Those changes can be done by anyone pretty easily. It should not take more than a day to add and test everything. If no problems arise it can be joined with other few changes for the log output also.

As for the setting up different packages for Windows, I cannot say, maybe @vandot could provide more info.

In regards to "official support for Windows", I cannot say that we should or should not support it. The Bee node does work on Windows (when started from terminal). This only comes down to supporting installing Windows service and supporting that way of using it. That to me seems like product decision.

**Comment by Eknir** [comment]
Hi @zbiljic , thanks again (and sorry for the late answer -- I realize this caused delays). I would like to support the windows package, most importantly to allow our users to use `bee-clef` easily. 

So, this should be the user story that needs to be achieved;

"As a user of Swarm who wants to earn gBZZ, I want to easily install and run Bee and Bee-clef, such that my computer will earn gBZZ in the background and my keys are secure and interoperable with Ethereum"

**Comment by zbiljic** [comment]
As far as having Clef also, that is one point that @vandot and myself discussed, however that should be separate from this issue. This issue is only related to having possibility for running Bee as a Windows Service.

Having `bee-clef` in tandem with `bee` would be whole separate issue in itself. Personally I have not looked at how Clef service works, or even if it possible to have it as Windows Service. As we found out for this issue, some custom code is required to have CLI application running as Windows Service. It very well might be possible that Clef does not have support for it (support being what was discussed for Bee). In that case alternatives would have to be explored.

Of course, there might that there is something that I am not aware, and invite @vandot to comment further on this.

**Comment by Eknir** [comment]
I created an issue for bee-clef. https://github.com/ethersphere/bee-clef/issues/3 . I understand that this is a separate issue. Let's indeed not convolute this issue with non-related things. Perhaps you and @vandot could spend some time (not more than 4h) to explore the possibilities of this and report your findings in the above-mentioned issue? 
Thanks @zbiljic

**Comment by Eknir** [comment]
This issue is completed. Could somebody please provide a concise set of instructions (as a comment below), outlining which steps a user needs to take in order to use Bee as a service on Microsoft? You can follow the example from our [documentation](https://docs.ethswarm.org/docs/installation/quick-start)

**Comment by zbiljic** [comment]
@Eknir Even though the Bee now supports starting it as a Windows service, the intention was not for the user to manually create the service. After future tickets for `chocolatey` and `scoop` documentation should be updated.

**Comment by Eknir** [comment]
@zbiljic , putting this in the icebox. @vandot , is it on your radar to get `bee` in `scoop`/`chocolatey`?

**Comment by chawyehsu** [comment]
I think this issue didn't solve yet. I [created](https://github.com/chawyehsu/dorado/commit/712aecd986c69a2dee32d78d5256f0bad13a9109) my bee manifest for `scoop` with a custom service helper for fast installing/uninstalling bee service, then I encounter the issue, it can't start and just fails with 1053 error.

screenshot:
![bee](https://user-images.githubusercontent.com/5764917/118815015-5e0e1400-b8e3-11eb-9e75-cc7f731fa74b.JPG)
