### ISSUE TITLE
Uploaded /file with swarm-tag-uid doesn't update tag

### ISSUE THREAD

**Issue by ldeffenb** [ethersphere/bee#984]
#### Summary
Uploaded a file with the /file API and included a swarm-tag-uid header with a UID received from a POST to /tags.  Subsequently querying the tag status with /tags/UID doesn't seem to change the values.  I get the following:

curl http://127.0.0.1:8080/tags/2110529053
{"total":0,"split":10,"seen":10,"stored":10,"sent":0,"synced":0,"uid":2110529053,"name":"unnamed_tag_1605822913","address":"","startedAt":"2020-11-19T16:55:13.9823185-05:00"}

#### Steps to reproduce
1) Create a tag UID via POST to /tags
2) Upload a file with a POST to /file and include the returned UID in a swarm-tag-uid header.
3) Poll the tag by GETting /tags/UID

#### Expected behavior
I expected at least the "sent" and "synced" values to update.

#### Actual behavior
"sent" and "synced" (and "total") remain 0.  Address is also not populated, but I'm not sure if it should have changed to the CID?

I'm trying to find a way to determine if an uploaded file has been split and successfully sent/synced to the network.

**Comment by ldeffenb** [comment]
Actually, I just realized that the file(s) I'm sending have already been uploaded to this node before, so it is likely that they won't be sent again.

But what is the actual expected behavior of the tag in the event that chunks of the file (like a file that shares some duplicate content with another file) have already been uploaded?  How can a client watching a tag's values know that the file has been fully processed?

**Comment by ldeffenb** [comment]
Pushed new files and got the tag statuses shown below.  So the new questions are:

What is "seen"?  And why does it always seem to be 1?

And the 3rd tag is either not done pushing or it actually did share a chunk with some other previous file?  I'll check that one again when the pusher finally catches up with my uploading.

curl http://127.0.0.1:8080/tags/1699341019
{"total":0,"split":5,"seen":1,"stored":5,"sent":4,"synced":4,"uid":1699341019,"name":"unnamed_tag_1605824879","address":"","startedAt":"2020-11-19T17:27:59.4186194-05:00"}

curl http://127.0.0.1:8080/tags/520575113
{"total":0,"split":5,"seen":1,"stored":5,"sent":4,"synced":4,"uid":520575113,"name":"unnamed_tag_1605824982","address":"","startedAt":"2020-11-19T17:29:42.7809947-05:00"}

curl http://127.0.0.1:8080/tags/2659129244
{"total":0,"split":5,"seen":1,"stored":5,"sent":3,"synced":3,"uid":2659129244,"name":"unnamed_tag_1605825033","address":"","startedAt":"2020-11-19T17:30:33.1313959-05:00"}

**Comment by ldeffenb** [comment]
Ok, I stopped uploading more and more files, waited for the pusher to finish up and queried the 3rd tag again and it appears to have finished, if "seen" is added to "sent" and "synced" to get "split" and "stored".  Strange that "total" insists on remaining zero...

curl http://127.0.0.1:8080/tags/2659129244
{"total":0,"split":5,"seen":1,"stored":5,"sent":4,"synced":4,"uid":2659129244,"name":"unnamed_tag_1605825033","address":"","startedAt":"2020-11-19T17:30:33.1313959-05:00"}

**Comment by zbiljic** [comment]
The 'tags' API comes up misunderstood at the moment. There is an overall issue #918 that aims to "simplify" general feel of it.

Details about what each field means can be found in the file [`pkg/tags/tag.go `](https://github.com/ethersphere/bee/blob/f8054e91c87c22dfa6c0b8dd13c41e6d4792dea6/pkg/tags/tag.go):
```go
Total  int64 // total chunks belonging to a tag
Split  int64 // number of chunks already processed by splitter for hashing
Seen   int64 // number of chunks already seen
Stored int64 // number of chunks already stored locally
Sent   int64 // number of chunks sent for push syncing
Synced int64 // number of chunks synced with proof
```

I mentioned some things on other issues maybe, however in relation to this one:
- `split` is incremented during processing of a file (uploaded content) into chunks
- after the chunks is stored, the `stored` is implemented
- in case some chunk was already present in local storage (uploaded again or common section), the `seen` is incremented
  - in that case `synced` will not be incremented
- otherwise (chunk was just added), that chunk will be moved to a queue which will distribute chunk to other peers
  - each time chunk is sent to some other peer, the `seen` is incremented
    - the `seen` count happens for each sending of chunk
    - it may happen that whole process does not complete, and this `seen` value may be increased above maximum number of chunks that were created
  - once the chunk is pushed to some other peer, and is confirmed as received, the `synced` field is incremented
- the `total` will only be changed once the 'tag' is marked that done splitting happened; at that point value of `split` will be copied into `total`, and (optional) address added to tag
  - if the user directly creates tag manually, then "done splitting" action must be manual also (via `PATCH /tags/{id}` request)
  - if the tag is created automatically (during upload to some endpoint), once syncing process completes, it will update `total` and `address` tag values

Back to the issue, when uploading something, if `split == seen + synced` it can be said that content is pushed to the network.
Total will not be changed in described steps until tag is manually `PATCH`-ed, which will mark it complete.
After uploading something, the `split` will represent number of chunks for that content, `seen` and `synced` will be incremented (depending on local chunks present), and in the end addition of those two values should be equal to `split`.
The `sent` may be incremented above `split` as is represents actual sending of chunk to peers.
If you just care about state of "single" file upload (or any other structure apart from chunk), you can just upload, without creating tag before, and use tag ID from response header to check state of the upload (it should have `total` once completed).

**Comment by ldeffenb** [comment]
> The 'tags' API comes up misunderstood at the moment. There is an overall issue #918 that aims to "simplify" general feel of it.
> 
> Details about what each field means can be found in the file [`pkg/tags/tag.go `](https://github.com/ethersphere/bee/blob/f8054e91c87c22dfa6c0b8dd13c41e6d4792dea6/pkg/tags/tag.go):
> 
> ```go
> Total  int64 // total chunks belonging to a tag
> Split  int64 // number of chunks already processed by splitter for hashing
> Seen   int64 // number of chunks already seen
> Stored int64 // number of chunks already stored locally
> Sent   int64 // number of chunks sent for push syncing
> Synced int64 // number of chunks synced with proof
> ```
> 
><snip>
> 
> * otherwise (chunk was just added), that chunk will be moved to a queue which will distribute chunk to other peers
>   
>   * each time chunk is sent to some other peer, the `seen` is incremented
>     
>     * the `seen` count happens for each sending of chunk
>     * it may happen that whole process does not complete, and this `seen` value may be increased above maximum number of chunks that were created
>   * once the chunk is pushed to some other peer, and is confirmed as received, the `synced` field is incremented
> <snip>
> Back to the issue, when uploading something, if `split == seen + synced` it can be said that content is pushed to the network.
> <snip>
> After uploading something, the `split` will represent number of chunks for that content, `seen` and `synced` will be incremented (depending on local chunks present), and in the end addition of those two values should be equal to `split`.
> The `sent` may be incremented above `split` as is represents actual sending of chunk to peers.

I believe the comments stating "seen" above should actually be "sent"?  Except for the completion test of seen+synced.

**Comment by zbiljic** [comment]
@ldeffenb I could not see your comment on GitHub, but did see it from the email.
You are correct in your comment, I was taken by the flow, and did make mistake. I have updated my comment accordingly (while also leaving original text with strikethrough).
