### ISSUE TITLE
Query existing tags?

### ISSUE THREAD

**Issue by ldeffenb** [ethersphere/bee#985]
#### Summary
I've been creating tags and uploading files with those tag UIDs, but is there a way to query what tags actually exist?  If my upload process doesn't complete cleanly, I'd need to be able to query the tags to delete them as no longer needed.

And can tag creation specify a name so that my client can recognize a queried tag as one that it created?

#### Steps to reproduce
1) Create a tag
2) Upload a file using that tag
3) loop 1 and 2 for a while resulting in lots of existing tags

How to know what tags were created in the event that the 1/2 loop fails?

#### Expected behavior
Ability to query existing tags so that they can be checked and/or cleaned up (deleted).

#### Actual behavior
Created tag UIDs seem to be invisible once created.

**Comment by Eknir** [comment]
@ldeffenb , you must have been creating a lot of tags. 
Just so that I understand your issue clearly;

First issue: the probability of collision in the createTag function is big. Solution: increase the length of the tag.
Second issue: No possibility to query existing tags. You would like to call to the bee node and request all existing tag-uids, potentially filtering on name

**Comment by Eknir** [comment]
This one is completed: https://docs.ethswarm.org/api/#tag/Tag/paths/~1tags/get
